"""Native RGB observations transcribed before contour or pair outcome exposure."""
from direct_morphology2_common import *
from collections import Counter
UNKNOWN={36:'Detached short trace; association with adjacent connected writing is unresolved.',42:'Faint curved trace/tail; full extent cannot be bounded confidently from RGB.',47:'Partial curved trace near a neighboring-row tall structure; possible contact/source continuation outside initial raster envelope.',51:'Possible faint contact with S052; separate and associated-parent alternatives retained.',52:'Possible faint contact with S051; separate and associated-parent alternatives retained.',55:'Possible faint contact with S056; separate/connected alternatives not decided.',56:'Possible faint contact with S055; separate/connected alternatives not decided.',63:'Two uprights with upper head/neighbor association unresolved; writing confirmed, full parent extent unknown.',64:'Tall trace and lower loop near another row; contact/ownership unresolved.',74:'Faint curved structure across provisional row aids; source evidence insufficient for full outline/extent.',78:'Small writing ink region; faint photographic edge/extent not resolved.',80:'Small writing ink region; faint photographic edge/extent not resolved.',89:'Small writing ink region; faint photographic edge/extent not resolved.',94:'Upper curved traces and lower branch near neighboring row; compound/contact alternative unresolved.',95:'Small writing ink region; faint photographic edge/extent not resolved.',112:'Short trace with adjacent larger curved trace; faint contact/association unresolved.',128:'Narrow vertical fragment; visible source continuation beyond initial raster envelope.',134:'Upper ordinary trace near lower paired structure; neighboring-row contact/compound cannot be decided.',144:'Faint multi-part tall structure near another-row trace; extent/contact unresolved.',161:'Upper trace and lower tall/frame structure cross provisional rows; ownership/whole-parent contact unresolved.',172:'Connected ordinary traces near lower-row tall structure; source contact vs one parent unresolved.',173:'Detached upper short trace; association with nearby writing remains unresolved.',178:'Upper ordinary writing touches/approaches lower-row structure; whole-parent ownership unresolved.',181:'Raster foot/stem excludes visible upper long bridge/head. Extended RGB retained; association/full connected-parent extent unresolved, not certified by finite foot shape.',183:'Upper ordinary traces and lower tall structure near another row; contact/whole ownership unresolved.',186:'Multi-height writing near neighboring row; connected compound versus incidental contact unresolved.',188:'Tall curved structure close to neighboring-row trace; extent/ownership not confidently isolated.'}
COMPOUND={4,7,9,10,16,18,25,28,30,33,35,44,46,48,53,54,58,59,60,62,65,66,68,72,79,81,83,84,85,87,90,92,96,98,102,104,105,106,108,110,111,113,114,120,123,127,138,139,142,145,149,150,153,154,156,163,167,168,171,174,175,176,180,182,185,187}
def main():
    guard();verify();assert not (D/'SOURCE_SEAL.json').exists();rr=read_json(D/'source_location_aids.json')['parents'];out=[]
    for r in rr:
        n=int(r['audit_id'][1:]);unknown=n in UNKNOWN;note=UNKNOWN[n] if unknown else 'Writing trace visible in nativeRGB; full observed connected-parent organization isolated from contextual neighboring ink. Native envelope remains a raster-location aid, not pixel-perfect source truth.'
        if n in [122,133]:note+=' Extended RGB shows neighboring-row overhang with visible separation; no join inferred.'
        if n in [148,149]:note+=' Extended RGB distinguishes writing in separate neighboring horizontal rows; no cross-row join inferred.'
        out.append(dict(parent_id=r['parent_id'],audit_id=r['audit_id'],caption=r['caption'],native_source=r['native_source'],native_bbox=r['native_bbox'],membership='confirmed_writing',source_parent_status='unknown_parent_extent' if unknown else 'resolved_whole_parent',source_extent_resolved=not unknown,possible_join=unknown and n not in [42,74,78,80,89,95],possible_split=unknown and n not in [36,42,74,78,80,89,95,128,173],detached_association_unknown=n in [36,173],faint_or_insufficient_extent=n in [42,74,78,80,89,95,128,144],neighboring_row_contact_possible=n in [47,63,64,94,134,144,161,172,178,183,186,188],possible_compound_connected_structure=n in COMPOUND,field_edge_location_aid=r['field_edge'],registered_field_row_aids=r['field_rows'],row_ownership_not_certified_from_body_projection=True,note=note))
    alternatives=[dict(audit_ids=['S051','S052'],relation='possible_faint_join_or_separate',full_parent_geometry=None),dict(audit_ids=['S055','S056'],relation='possible_faint_join_or_separate',full_parent_geometry=None),dict(audit_ids=['S181'],relation='possible_larger_source_extent_than_primary_raster',context='figures/direct_morphology_trial2/S181_extended_context.png',observed_context_bbox=[1060,280,1450,560],full_parent_geometry=None)]
    save(D/'source_decisions.json',dict(decided_at_utc=now(),parents=out,extent_alternatives=alternatives,native_RGB_reviewed_all_192=True,full_field_and_individual_parent_crops_reviewed=True,extended_contexts=read_json(D/'extended_RGB_source_contexts.json'),distances_nearest_neighbors_V3_features_transcriptions_not_shown=True,same_AI_adjudicator_not_independent_human=True,uncertainty='Writing membership and isolated full extent are separate judgments. Connected compounds stay whole; possible incidental contacts/splits and detached associations retain unknown full geometry. No letters/internal graphemes/stroke-order inference. Bounding-box aids are not physical-pixel ground truth.'))
    paths=[D/'source_decisions.json',D/'source_location_aids.json',D/'extended_RGB_source_contexts.json',OUT/'src/adjudicate_direct_morphology2_sources.py',OUT/'src/prepare_direct_morphology2_sources.py']+list((D/'parent_masks').glob('*.png'))+list((G/'native_parents').glob('*.png'))+list(G.glob('source_cap*.png'))+list(G.glob('*_extended_context.png'));seal(paths,D/'SOURCE_SEAL.json');print('Source decisions',dict(Counter(r['source_parent_status'] for r in out)),flush=True)
if __name__=='__main__':main()
