"""Second-candidate RGB source judgments made without its audit key."""
from common import OUT,read_json,write_json
from collections import Counter
ROOT=OUT/'data/observations/recurrence_v3_structural_candidate'
DIFFERENT={2:'Closed ring versus loop with attached right trace',3:'Two-arch bridge versus short single hooked arch',5:'Compact loop with upper trace versus open horizontal bridge',8:'Loop and long descending tail versus short terminal',11:'Paired uprights versus vertically stacked loops',15:'Left appended open curve versus loop pair without appendix',17:'Two upright/bridge structure versus single curved terminal',23:'Compact open hook versus long upper curve/lower terminal',24:'Oblique branched lower attachment versus single descending tail',29:'Extended arch/loop assembly differs',30:'Lower branch organization differs',42:'Long curved terminal versus closed ring',43:'Ring versus loop with upper-right trace',51:'Ring versus attached upper/right trace',53:'Single descending upright bridge versus paired uprights',54:'Single long tail versus oblique branched lower trace',55:'Connected extended assembly has different appended lower contour',57:'Open hooked trace versus short oblique terminal',59:'Compact loop/upper-right trace versus open horizontal assembly',62:'Added connected left hook changes whole parent',64:'Ring versus upper/right attached trace',68:'Added lower horizontal contact changes compound connectivity',69:'Added left contour changes whole connected parent',70:'Extended lower arch organization differs',76:'Connected upright/bridge assembly versus loop/branch assembly',79:'One descending upright versus two',80:'Long curved descending structure versus small terminal'}
UNKNOWN={14:'Pale bridge endpoint/contact not resolved',20:'Pale bridge endpoint/contact not resolved',28:'Pale upper/lower bridge contact not resolved',41:'Faint short trace continuity not resolved',49:'Small upper-left closure not decidable from this photograph/crop'}

def main():
    from recurrence_guard_v3 import require_unfrozen
    require_unfrozen(ROOT)
    judgments=[dict(pair_id=f'A{i:03d}',judgment='different' if i in DIFFERENT else 'unknown' if i in UNKNOWN else 'same_structural_hypothesis',reason=DIFFERENT.get(i,UNKNOWN.get(i,'Same contour/connectivity organization with slant, width, ink density or proportion variation')),basis='Native RGB source pair, proposed same/different classes hidden; no inherited labels or positional/group-pair outcomes') for i in range(1,81)]
    write_json(ROOT/'pair_source_judgments_before_key.json',judgments);pairs=read_json(ROOT/'pair_audit_key.json');lookup={r['pair_id']:r for r in judgments};table=Counter((p['kind'],lookup[p['pair_id']]['judgment']) for p in pairs)
    pos=sum(v for (k,j),v in table.items() if k=='positive');neg=sum(v for (k,j),v in table.items() if k=='hard_negative');true_diff=sum(v for (k,j),v in table.items() if j=='different')
    result=dict(counts={f'{k}:{j}':v for (k,j),v in table.items()},positive_agreement=table['positive','same_structural_hypothesis']/pos,apparent_hard_negative_same_structure_fraction=table['hard_negative','same_structural_hypothesis']/neg,false_acceptance_among_source_judged_different_pairs=table['positive','different']/max(1,true_diff),definition='Source-judged different pairs supply the actual negative ground truth. Model-class-different proposals judged same expose false separation; they are not true negatives.',independent_raters=1,unknown_count=len(UNKNOWN),source_pair_agreement_is_single_agent=True)
    write_json(ROOT/'pair_audit_results.json',result);print(result,flush=True)

if __name__=='__main__':main()
