from direct_morphology_common import *
from sklearn.metrics import roc_auc_score
from scipy.stats import spearmanr
from collections import Counter
import numpy as np,cv2

def contour_matrix(shapes):
    edges=np.array([s.astype(bool)&~cv2.erode(s,np.ones((3,3),np.uint8)).astype(bool) for s in shapes]);edge=edges.reshape(len(edges),-1).astype(np.float32);maps=np.array([cv2.distanceTransform((~s).astype(np.uint8),cv2.DIST_L2,3) for s in edges]).reshape(len(edges),-1);counts=edge.sum(1);assert np.all(counts>0);one=(maps@edge.T)/counts[None,:];size=shapes.shape[1];support=size-2*max(2,round(size/16));dd=(one+one.T)/(2*support);np.fill_diagonal(dd,0);return dd
def sdf_matrix(fields):
    x=fields.reshape(len(fields),-1).astype(np.float64);norm=(x*x).mean(1);dd=np.sqrt(np.maximum(0,norm[:,None]+norm[None,:]-2*(x@x.T)/x.shape[1]));np.fill_diagonal(dd,0);return dd
def envelopes(parents,matrix):
    n=len(parents);low=np.zeros((n,n));high=np.zeros((n,n));primary=np.array([r['primary_index'] for r in parents]);base=matrix[np.ix_(primary,primary)]
    for i in range(n):
        for j in range(i,n):
            d=matrix[np.ix_(parents[i]['candidate_indices'],parents[j]['candidate_indices'])];low[i,j]=low[j,i]=float(d.min());high[i,j]=high[j,i]=float(d.max())
    return base,low,high
def auc(rows,key):return float(roc_auc_score([r['rating']==2 for r in rows],[-r[key] for r in rows])) if len({r['rating'] for r in rows})==2 else None
def run():
    guard();verify();verify_seal(D/'SHAPE_SEAL.json');assert not (D/'DISTANCE_SEAL.json').exists();data=read_json(D/'source_parent_ensembles.json');parents=data['parents'];candidates=data['candidates'];fields=np.load(D/'direct_image_fields.npz');print('Computing direct candidate distance matrices',len(candidates),flush=True);contour=contour_matrix(fields['shape64']);morph=sdf_matrix(fields['sdf64']);base,low,high=envelopes(parents,contour);sbase,slow,shigh=envelopes(parents,morph);primary=np.array([r['primary_index'] for r in parents]);res32=contour_matrix(fields['shape32'][primary]);res128=contour_matrix(fields['shape128'][primary]);np.savez_compressed(D/'direct_distance_matrices.npz',candidate_contour64=contour,candidate_sdf64=morph,primary_contour64=base,observed_contour_low=low,observed_contour_high=high,primary_sdf64=sbase,observed_sdf_low=slow,observed_sdf_high=shigh,primary_contour32=res32,primary_contour128=res128)
    fixed=read_json(D/'reused_source_pairs.json');ratings={r['pair_id']:r['rating'] for r in read_json(D/'reused_source_ratings.json')['pairs']};rr=[]
    for r in fixed:
        i=r['anchor_parent'];j=r['reference_parent'];rr.append(dict(**r,rating=ratings[r['pair_id']],source_extents_resolved=parents[i]['source_extent_resolved'] and parents[j]['source_extent_resolved'],contour64=float(base[i,j]),contour32=float(res32[i,j]),contour128=float(res128[i,j]),sdf64=float(sbase[i,j]),observed_low=float(low[i,j]),observed_high=float(high[i,j]),complete_physical_interval=None))
    binary=[r for r in rr if r['rating'] in [0,2] and r['source_extents_resolved']];ordinal=[r for r in rr if r['rating'] in [0,1,2] and r['source_extents_resolved']];metrics={}
    for name in ['contour64','sdf64','contour32','contour128']:metrics[name]=dict(auc=auc(binary,name),ordinal_spearman=float(spearmanr([r['rating'] for r in ordinal],[-r[name] for r in ordinal]).statistic))
    rng=np.random.default_rng(20261017);caps=sorted({r['caption'] for r in binary});bb=[]
    for _ in range(2000):
        sample=[r for cap in rng.choice(caps,len(caps),replace=True) for r in binary if r['caption']==cap];aa=auc(sample,'contour64')
        if aa is not None:bb.append(aa)
    # Interval-identifiable ordering: all same-vs-different comparisons, not a new source classification.
    pos=[r for r in binary if r['rating']==2];neg=[r for r in binary if r['rating']==0];certain_correct=sum(a['observed_high']<b['observed_low'] for a in pos for b in neg);certain_wrong=sum(a['observed_low']>b['observed_high'] for a in pos for b in neg);total=len(pos)*len(neg)
    pair_result=dict(all_pairs=len(rr),rating_counts=dict(Counter(str(r['rating']) for r in rr)),binary_n=len(binary),positive_n=len(pos),negative_n=len(neg),caption_n=len(caps),metrics=metrics,primary_contour_caption_bootstrap95=np.percentile(bb,[2.5,97.5]).tolist(),interval_ordering=dict(positive_negative_comparisons=total,certain_correct=certain_correct,certain_wrong=certain_wrong,overlapping_or_tied=total-certain_correct-certain_wrong,guaranteed_correct_fraction=certain_correct/total,possible_correct_upper_fraction=1-certain_wrong/total,not_a_calibrated_AUC_confidence_interval=True),pairs=rr,primary_results_not_fresh_confirmation=True,full_physical_distance_intervals_not_estimated=True,limitations='Reused source pairs selected previously by multiple methods, same-AI judgments, repeated anchors/references and known contour outcome. Caption bootstrap is conditional descriptive precision. Min/max candidate envelopes cannot establish physical equivalence; compared pair-order events are dependent.')
    save(T/'source_similarity_and_envelopes.json',pair_result)
    ref=np.array([i for i,r in enumerate(parents) if r['corpus']=='reference' and r['source_extent_resolved']]);fresh=[i for i,r in enumerate(parents) if r['corpus']=='fresh' and r['source_extent_resolved']];retr=[]
    for i in fresh:
        js=ref[np.array([parents[j]['caption']!=parents[i]['caption'] for j in ref])];order=js[np.argsort(base[i,js])];best=int(order[0]);other=order[1:];guaranteed=bool(high[i,best]<low[i,other].min());possible=order[low[i,order]<=high[i,best]]
        retr.append(dict(parent_id=parents[i]['parent_id'],audit_id=parents[i]['audit_id'],caption=parents[i]['caption'],primary_nearest=parents[best]['parent_id'],nearest_observed_distance=float(base[i,best]),nearest_observed_interval=[float(low[i,best]),float(high[i,best])],primary_nearest_certain_under_observed_candidates=guaranteed,reference_candidates_not_excluded=int(len(possible)),nearest32=parents[int(js[np.argmin(res32[i,js])])]['parent_id'],nearest128=parents[int(js[np.argmin(res128[i,js])])]['parent_id'],no_source_membership_decision_from_retrieval=True))
    save(T/'continuous_reference_retrieval.json',dict(source_resolved_fresh_n=len(retr),reference_n=len(ref),certain_nearest_n=sum(r['primary_nearest_certain_under_observed_candidates'] for r in retr),median_not_excluded=float(np.median([r['reference_candidates_not_excluded'] for r in retr])),same_nearest32_n=sum(r['primary_nearest']==r['nearest32'] for r in retr),same_nearest128_n=sum(r['primary_nearest']==r['nearest128'] for r in retr),parents=retr,no_class_assignments=True,scope='Nearest image resemblance only; uncertainty can leave multiple admissible neighbors. These ranks are similarity ranks, not manuscript ordinal positions. No source parent boundary settled by these distances.'))
    uncertainty=[]
    for i,r in enumerate(parents):
        p=r['primary_index'];alt=[z for z in r['candidate_indices'] if candidates[z]['role']!='slant_sensitivity'];sl=[z for z in r['candidate_indices'] if candidates[z]['role']=='slant_sensitivity'];uncertainty.append(dict(parent_id=r['parent_id'],audit_id=r['audit_id'],corpus=r['corpus'],source_extent_resolved=r['source_extent_resolved'],candidate_n=len(r['candidate_indices']),missing_contrast=any(q['missing'] for q in r['correspondence']),split_contrast=any(q['split'] for q in r['correspondence']),merge_contrast=any(q['merge'] for q in r['correspondence']),max_primary_to_raster_candidate=float(contour[p,alt].max()),max_primary_to_slant=float(contour[p,sl].max()),complete_extent_embedding_available=r['source_extent_resolved'],physical_interval=None))
    def summary(rs):return dict(confirmed=len(rs),primary_shape_available=len(rs),source_resolved=sum(r['source_extent_resolved'] for r in rs),unknown_full_extent=sum(not r['source_extent_resolved'] for r in rs),split_cases=sum(r['split_contrast'] for r in rs),merge_cases=sum(r['merge_contrast'] for r in rs),missing_cases=sum(r['missing_contrast'] for r in rs),median_candidate_n=float(np.median([r['candidate_n'] for r in rs])),raster_spread_median=float(np.median([r['max_primary_to_raster_candidate'] for r in rs])),raster_spread95=float(np.percentile([r['max_primary_to_raster_candidate'] for r in rs],95)),slant_spread_median=float(np.median([r['max_primary_to_slant'] for r in rs])))
    save(T/'representation_and_source_uncertainty.json',dict(all=summary(uncertainty),fresh=summary([r for r in uncertainty if r['corpus']=='fresh']),reference=summary([r for r in uncertainty if r['corpus']=='reference']),parents=uncertainty,uncertainty_not_eliminated_by_direct_coordinates=True,physical_embedding_meaning='Source-resolved means the photograph qualifies the whole extent; raster candidate positions remain measured approximations, not certified physical contour. Uncertain extents only have observed-part candidate vectors plus explicit UNKNOWN full-parent geometry.'))
    gate=dict(all_primary_nonempty=len(parents)==217 and bool(np.all(fields['shape64'][primary].sum((1,2))>0)),uncertain_extents_remain_unknown=all(r['full_extent_state']=='unknown' and r['full_physical_distance_bounded'] is False for r in parents if not r['source_extent_resolved']),no_discrete_classes_or_required_semantic_features=all(r['source_family_or_class'] is None and r['semantic_features_required'] is False for r in parents),descriptive_auc=metrics['contour64']['auc']>=.75,descriptive_pairs=len(binary)>=120,six_captions=len(caps)>=6,fresh_independent_confirmation=False)
    save(T/'acceptance_summary.json',dict(gates=gate,operational_feasibility=all(gate[k] for k in ['all_primary_nonempty','uncertain_extents_remain_unknown','no_discrete_classes_or_required_semantic_features']),descriptive_source_predictivity=all(gate[k] for k in ['descriptive_auc','descriptive_pairs','six_captions']),fresh_generalization_validated=False,source_truth_or_segmentation_improved=False,no_downstream_assays=True))
    seal([D/'direct_distance_matrices.npz',OUT/'src/evaluate_direct_morphology.py']+list(T.glob('*.json')),D/'DISTANCE_SEAL.json');print('Direct morphology',metrics,'certain nearest',sum(r['primary_nearest_certain_under_observed_candidates'] for r in retr),'/',len(retr),flush=True)
if __name__=='__main__':run()
