from direct_morphology2_common import *
from evaluate_direct_morphology import contour_matrix,sdf_matrix,envelopes
from sklearn.metrics import roc_auc_score
from scipy.stats import spearmanr,rankdata
from collections import Counter
import numpy as np

def auc(rows,key,weights=None):
    y=np.array([r['rating']==2 for r in rows]); x=np.array([-r[key] for r in rows]); w=np.ones(len(rows)) if weights is None else np.array(weights)
    if not (w[y].sum()>0 and w[~y].sum()>0):return None
    return float(roc_auc_score(y,x,sample_weight=w))

def main():
    guard(); verify(); assert not (D/'DISTANCE_SEAL.json').exists()
    for s in ['SHAPE','RATING','REPEAT']:verify_seal(D/(s+'_SEAL.json'))
    save(D/'EVALUATION_DECISION_RULE.json',dict(registered_before_new_prediction_computation_at_utc=now(),rule='After final freeze: inadequate sample or bootstrap support -> not estimable; all registered gates including exact replay and preserved unknowns -> supported within qualified source sample; any failed metric gate with adequate support -> not supported by this confirmatory trial. No secondary-metric substitution; no partial pass invented.'))
    seal([D/'EVALUATION_DECISION_RULE.json',OUT/'src/evaluate_direct_morphology2.py'],D/'EVALUATOR_SEAL.json')
    data=read_json(D/'source_parent_ensembles.json'); parents=data['parents']; cand=data['candidates']; fields=np.load(D/'direct_image_fields.npz'); print('Computing frozen metrics after source ratings seal',flush=True)
    cc=contour_matrix(fields['shape64']); ss=sdf_matrix(fields['sdf64']); b,l,h=envelopes(parents,cc); sb,sl,sh=envelopes(parents,ss); primary=np.array([p['primary_index'] for p in parents]); b32=contour_matrix(fields['shape32'][primary]); b128=contour_matrix(fields['shape128'][primary]); np.savez_compressed(D/'direct_distance_matrices.npz',candidate_contour64=cc,candidate_sdf64=ss,primary_contour64=b,observed_contour_low=l,observed_contour_high=h,primary_sdf64=sb,observed_sdf_low=sl,observed_sdf_high=sh,primary_contour32=b32,primary_contour128=b128)
    loc=read_json(D/'source_location_aids.json')['parents']; by={p['parent_id']:i for i,p in enumerate(parents)}; key={p['pair_id']:p for p in read_json(D/'pair_pool_hidden_key.json')['pairs']}; rr=[]
    for r in read_json(D/'source_similarity_decisions.json')['pairs']:
        q=key[r['pair_id']]; i=by[loc[q['left_index']]['parent_id']]; j=by[loc[q['right_index']]['parent_id']]; assert parents[i]['caption']!=parents[j]['caption']; assert parents[i]['source_extent_resolved'] and parents[j]['source_extent_resolved']
        rr.append(dict(pair_id=r['pair_id'],rating=r['rating'],left_parent=parents[i]['parent_id'],right_parent=parents[j]['parent_id'],caption_left=parents[i]['caption'],caption_right=parents[j]['caption'],sampling_method=q['sampling_method'],source_extents=['source_resolved','source_resolved'],contour64=float(b[i,j]),sdf64=float(sb[i,j]),contour32=float(b32[i,j]),contour128=float(b128[i,j]),aspect_only=q['native_aspect_difference'],contour_observed_low=float(l[i,j]),contour_observed_high=float(h[i,j]),sdf_observed_low=float(sl[i,j]),sdf_observed_high=float(sh[i,j]),physical_distance_interval=None))
    binary=[r for r in rr if r['rating'] in [0,2]]; ordinal=[r for r in rr if r['rating'] in [0,1,2]]; names=['contour64','aspect_only','sdf64','contour32','contour128']; metrics={k:dict(AUROC=auc(binary,k),ordinal_spearman=float(spearmanr([r['rating'] for r in ordinal],[-r[k] for r in ordinal]).statistic)) for k in names}
    caps=sorted({c for r in binary for c in [r['caption_left'],r['caption_right']]},key=int); rng=np.random.default_rng(read_json(D/'PLAN.json')['seed']+2); bb=[]; dd=[]
    for _ in range(2000):
        counts=Counter(rng.choice(caps,len(caps),replace=True)); w=[counts[r['caption_left']]*counts[r['caption_right']] for r in binary]; aa=auc(binary,'contour64',w); ab=auc(binary,'aspect_only',w)
        if aa is not None and ab is not None:bb.append(aa); dd.append(aa-ab)
    ci=np.percentile(bb,[2.5,97.5]).tolist() if bb else None; dci=np.percentile(dd,[2.5,97.5]).tolist() if dd else None; cats={v:{c for r in binary if r['rating']==v for c in [r['caption_left'],r['caption_right']]} for v in [0,2]}; counts=Counter(str(r['rating']) for r in rr); gatespec=read_json(D/'PLAN.json')['gates']; delta=metrics['contour64']['AUROC']-metrics['aspect_only']['AUROC']
    sample_gates=dict(caption_support=len(caps)>=gatespec['caption_n_min'],binary_support=len(binary)>=gatespec['binary_n_min'],same_support=counts['2']>=gatespec['same_n_min'],different_support=counts['0']>=gatespec['different_n_min'],each_category_caption_support=all(len(cats[v])>=gatespec['each_category_endpoint_caption_n_min'] for v in [0,2]),valid_bootstrap_support=len(bb)>=gatespec['valid_bootstrap_n_min'])
    metric_gates=dict(primary_contour64_AUROC=metrics['contour64']['AUROC']>=gatespec['primary_contour64_AUROC_min'],caption_bootstrap_lower=ci is not None and ci[0]>=gatespec['bootstrap_contour64_lower_min'],aspect_delta=delta>=gatespec['aspect_delta_min'],paired_delta_bootstrap_lower=dci is not None and dci[0]>0)
    pos=[r for r in binary if r['rating']==2]; neg=[r for r in binary if r['rating']==0]; total=len(pos)*len(neg); correct=sum(a['contour_observed_high']<z['contour_observed_low'] for a in pos for z in neg); wrong=sum(a['contour_observed_low']>z['contour_observed_high'] for a in pos for z in neg)
    save(T/'primary_and_secondary_metrics.json',dict(pair_n=len(rr),binary_n=len(binary),rating_counts=dict(counts),caption_n=len(caps),category_caption_counts={str(k):len(v) for k,v in cats.items()},metrics=metrics,primary_caption_node_bootstrap95=ci,contour_minus_aspect=delta,paired_delta_bootstrap95=dci,valid_bootstrap_n=len(bb),requested_bootstrap_n=2000,bootstrap_seed=read_json(D/'PLAN.json')['seed']+2,bootstrap_definition='Two endpoint caption count products; shared weights for paired delta; conditional dependence-aware uncertainty, not independent rater uncertainty',sample_gates=sample_gates,metric_gates=metric_gates,strata={m:dict(n=len(rs),same_n=sum(r['rating']==2 for r in rs),metrics={k:auc(rs,k) for k in names}) for m in ['broad_random','aspect_matched'] for rs in [[r for r in binary if r['sampling_method']==m]]},leave_one_caption_out={cap:dict(n=len(rs),AUROC=auc(rs,'contour64'),aspect_AUROC=auc(rs,'aspect_only')) for cap in caps for rs in [[r for r in binary if cap not in [r['caption_left'],r['caption_right']]]]},interval_ordering=dict(comparisons=total,certain_correct=correct,certain_wrong=wrong,overlapping_or_tied=total-correct-wrong,guaranteed_correct_fraction=correct/total,possible_correct_upper_fraction=1-wrong/total,not_a_posterior_or_AUROC_confidence_interval=True),pairs=rr,no_interpretive_disposition_before_final_freeze=True,limitations='Same AI adjudicator; photograph overview exposure; parents reused across pairs; binary excludes partial/U; high-quality proposal-conditioned sample rather than manuscript census. Caption-node bootstrap addresses caption sharing but cannot cover systematic adjudication bias.'))
    ref=np.array([i for i,p in enumerate(parents) if p['corpus']=='separate_frozen_reference' and p['source_extent_resolved']]); fresh=[i for i,p in enumerate(parents) if p['corpus']=='fresh' and p['source_extent_resolved']]; retr=[]
    assert len(ref)==88 and not {parents[i]['caption'] for i in ref}&{parents[i]['caption'] for i in fresh}
    refprimary=primary[ref]; refcand=np.array([k for j in ref for k in parents[j]['candidate_indices']]); rcparent=np.array([j for j in ref for k in parents[j]['candidate_indices']])
    for i in fresh:
        order=ref[np.argsort(b[i,ref],kind='stable')]; best=int(order[0]); others=order[1:]; conservative=bool(h[i,best]<l[i,others].min()); possible=order[l[i,order]<=h[i,best]]; stable=True; query_changes=[]; ranks=[]
        # Shared query alternative is held constant in each comparison. Reference alternatives may vary independently.
        for q in parents[i]['candidate_indices']:
            nearest=int(ref[np.argmin(cc[q,refprimary])]);
            if nearest!=best:query_changes.append(dict(query_candidate=cand[q]['candidate_id'],reference=parents[nearest]['parent_id']))
            max_best=float(cc[q,parents[best]['candidate_indices']].max()); min_other=float(cc[q,refcand[rcparent!=best]].min()); stable &= max_best<min_other
            ranks.append(int(1+sum(float(cc[q,parents[j]['candidate_indices']].min())<max_best for j in others)))
        n32=int(ref[np.argmin(b32[i,ref])]); n128=int(ref[np.argmin(b128[i,ref])]); retr.append(dict(parent_id=parents[i]['parent_id'],audit_id=parents[i]['audit_id'],caption=parents[i]['caption'],extent_state=parents[i]['full_extent_state'],primary_nearest=parents[best]['parent_id'],primary_distance=float(b[i,best]),observed_envelope=[float(l[i,best]),float(h[i,best])],nearest_across_all_observed_alternatives=bool(stable),conservative_global_envelope_guarantee=conservative,not_excluded_neighbor_n=int(len(possible)),not_excluded_neighbors=[parents[j]['parent_id'] for j in possible],nearest32=parents[n32]['parent_id'],nearest128=parents[n128]['parent_id'],rank_spearman32=float(spearmanr(b[i,ref],b32[i,ref]).statistic),rank_spearman128=float(spearmanr(b[i,ref],b128[i,ref]).statistic),query_alternative_changes=query_changes,primary_neighbor_worst_observed_rank=max(ranks),physical_interval=None))
    save(T/'uncertainty_and_retrieval.json',dict(fresh_queries_n=len(fresh),reference_n=len(ref),all_alternative_stable_nearest_n=sum(r['nearest_across_all_observed_alternatives'] for r in retr),conservative_envelope_guarantee_n=sum(r['conservative_global_envelope_guarantee'] for r in retr),median_not_excluded_neighbors=float(np.median([r['not_excluded_neighbor_n'] for r in retr])),same_nearest32_n=sum(r['primary_nearest']==r['nearest32'] for r in retr),same_nearest128_n=sum(r['primary_nearest']==r['nearest128'] for r in retr),query_alternative_changes_n=sum(bool(r['query_alternative_changes']) for r in retr),rank_spearman32_median=float(np.median([r['rank_spearman32'] for r in retr])),rank_spearman128_median=float(np.median([r['rank_spearman128'] for r in retr])),parents=retr,neighbor_sets_are_not_classes=True,definition='Strict unique nearest under every observed query alternative and independent reference alternatives. Not-excluded set uses conservative pair envelopes against primary-neighbor upper distance. No full physical shape uncertainty bounds.',low_unique_stability_is_not_failure_gate=True))
    unc=[]
    for i,p in enumerate(parents):
        alt=[z for z in p['candidate_indices'] if cand[z]['role']!='slant_sensitivity']; slant=[z for z in p['candidate_indices'] if cand[z]['role']=='slant_sensitivity']; roles=[cand[z]['role'] for z in p['candidate_indices']]; unc.append(dict(parent_id=p['parent_id'],corpus=p['corpus'],extent_state=p['full_extent_state'],candidate_n=len(roles),split=any(cand[z]['split'] for z in p['candidate_indices']),merge=any(cand[z]['merge'] for z in p['candidate_indices']),missing=any(q['missing'] for q in p.get('correspondence',[])),maximum_raster_displacement=float(cc[p['primary_index'],alt].max()),maximum_slant_displacement=float(cc[p['primary_index'],slant].max()) if slant else None,full_parent_geometry=None if not p['source_extent_resolved'] else 'observed_candidates_only_not_certified_contour'))
    freshunc=[u for u in unc if u['corpus']=='fresh']; save(T/'representation_coverage_and_uncertainty.json',dict(fresh_confirmed_writing_n=len(freshunc),fresh_source_resolved_n=len(fresh),fresh_unknown_extent_n=len(freshunc)-len(fresh),candidate_n=len(cand),parents_n=len(parents),split_n=sum(u['split'] for u in freshunc),merge_n=sum(u['merge'] for u in freshunc),missing_contrast_n=sum(u['missing'] for u in freshunc),parents=unc,source_uncertainty_preserved=all(p['full_extent_state']=='unknown' and not p['full_physical_distance_bounded'] for p in parents if not p['source_extent_resolved']),all_primary_nonempty=bool(np.all(fields['shape64'][primary].sum((1,2))>0)),full_source_recall_not_estimated=True))
    seal([D/'direct_distance_matrices.npz']+list(T.glob('*.json'))+[OUT/'src/evaluate_direct_morphology2.py'],D/'DISTANCE_SEAL.json'); print('Prediction metrics and uncertainty diagnostics computed and sealed; interpretation deferred until final freeze',flush=True)
if __name__=='__main__':main()

