from dm2_robustness_common import *
from prepare_dm2_robustness import contrast_label,dyad
from collections import Counter
import numpy as np

def weighted_auc(labels,scores,weights):
    y=np.asarray(labels,dtype=bool);scores=np.asarray(scores);w=np.asarray(weights,dtype=float)
    if w.ndim==1:w=w[None,:]
    if not len(y):return np.full(len(w),np.nan)
    order=np.argsort(scores,kind='stable');ss=scores[order];start=np.r_[0,np.flatnonzero(np.diff(ss)!=0)+1];ww=w[:,order];yy=y[order];pos=np.add.reduceat(ww*yy,start,axis=1);neg=np.add.reduceat(ww*(~yy),start,axis=1);pn=pos.sum(1);nn=neg.sum(1);numerator=(pos*(np.cumsum(neg,axis=1)-neg*.5)).sum(1);den=pn*nn;out=np.full(len(w),np.nan);np.divide(numerator,den,out=out,where=den>0);return out
def interval(values):
    a=np.asarray(values);a=a[np.isfinite(a)];return np.percentile(a,[2.5,97.5]).tolist() if len(a) else None
def point(a):return None if not np.isfinite(a) else float(a)
def evaluate(rows,labels,counts,caps,frequency=None):
    y=np.asarray(labels);f=np.ones(len(rows)) if frequency is None else np.array(frequency);w=np.array([counts[:,caps.index(r['caption_left'])]*counts[:,caps.index(r['caption_right'])] for r in rows]).T if rows else np.empty((len(counts),0));w=w*f[None,:];score=np.array([-r['contour64'] for r in rows]);aspect=np.array([-r['aspect_only'] for r in rows]);bootstrap=weighted_auc(y,score,w);baseline=weighted_auc(y,aspect,w);p=weighted_auc(y,score,f)[0];a=weighted_auc(y,aspect,f)[0];v=np.isfinite(bootstrap)&np.isfinite(baseline);positive=int((y==1).sum());negative=int((y==0).sum());pc={c for r,z in zip(rows,y) if z==1 for c in [r['caption_left'],r['caption_right']]};nc={c for r,z in zip(rows,y) if z==0 for c in [r['caption_left'],r['caption_right']]};allcaps=pc|nc;degrees=Counter(p for r in rows for p in [r['left_parent'],r['right_parent']]);dyads=Counter(dyad(r) for r in rows)
    return dict(n=len(rows),positive_n=positive,negative_n=negative,caption_n=len(allcaps),positive_caption_n=len(pc),negative_caption_n=len(nc),unique_parent_n=len(degrees),maximum_parent_degree=max(degrees.values(),default=0),caption_dyad_n=len(dyads),maximum_dyad_degree=max(dyads.values(),default=0),AUROC=point(p),aspect_AUROC=point(a),contour_minus_aspect=point(p-a),caption_bootstrap95=interval(bootstrap),aspect_bootstrap95=interval(baseline),paired_delta_bootstrap95=interval(bootstrap-baseline),valid_bootstrap_n=int(v.sum()),bootstrap_n=len(counts),adequate_conditional_uncertainty=bool(positive>=5 and negative>=5 and len(pc)>=3 and len(nc)>=3 and len(allcaps)>=4 and v.sum()>=4500),selection_not_random_inference='Intervals condition on selected graph subset and source labels; independent parents still share captions',pair_ids=[r['pair_id'] for r in rows],category_weights_used=frequency is not None)

def agreement(a,b,weights):
    a=np.asarray(a);b=np.asarray(b);w=np.asarray(weights);known=np.isin(a,[0,1,2])&np.isin(b,[0,1,2]);den=w.sum();exact=float((w*(a==b)).sum()/den) if den else None;wk=w[known];aa=a[known].astype(int);bb=b[known].astype(int);c=np.zeros((3,3),float)
    for x,y,z in zip(aa,bb,wk):c[x,y]+=z
    total=c.sum();out=dict(exact=exact,resolved_n=int(known.sum()),unresolved_n=int((~known).sum()))
    if total:
        marginal=np.outer(c.sum(1),c.sum(0))/total**2;delta=abs(np.arange(3)[:,None]-np.arange(3)[None,:]);matrices=dict(unweighted=np.eye(3),linear=1-delta/2,quadratic=1-delta**2/4)
        for key,m in matrices.items():
            obs=float((c*m).sum()/total);expected=float((marginal*m).sum());out[key+'_agreement']=obs;out[key+'_kappa']=(obs-expected)/(1-expected) if expected<1 else None
    out['transition_weights']=c.tolist();return out

def main():
    guard();verify_base()
    for s in ['PROTOCOL','SUBSET','REPEAT_RATINGS']:verify_seal(D/(s+'_SEAL.json'))
    assert not (D/'ANALYSIS_SEAL.json').exists();spec=read_json(D/'PLAN.json');selections=read_json(D/'analysis_selections.json');source={r['pair_id']:r for r in read_json(BT/'primary_and_secondary_metrics.json')['pairs']};rows={r['pair_id']:dict(r,contour64=source[r['pair_id']]['contour64'],aspect_only=source[r['pair_id']]['aspect_only']) for r in selections['source_pair_metadata']};caps=sorted({c for r in rows.values() for c in [r['caption_left'],r['caption_right']]},key=int);rng=np.random.default_rng(spec['seed']+2);draws=rng.integers(0,len(caps),(5000,len(caps)));counts=np.stack([(draws==i).sum(1) for i in range(len(caps))],axis=1);np.savez_compressed(D/'caption_bootstrap_draws.npz',counts=counts,captions=np.array(caps));results=[]
    for i,s in enumerate(selections['analyses']):
        rr=[rows[p] for p in s['selected_pair_ids']];yy=[contrast_label(r,s['contrast']) for r in rr];result=dict(analysis_id=s['analysis_id'],source_filter=s['source_filter'],stratum=s['stratum'],contrast=s['contrast'],dependence=s['dependence'],**evaluate(rr,yy,counts,caps));greedy=[]
        for g in s['greedy_selection_sensitivity']:
            gr=[rows[p] for p in g['pair_ids']];lab=[contrast_label(r,s['contrast']) for r in gr];values=weighted_auc(lab,[-r['contour64'] for r in gr],np.ones(len(gr)));greedy.append(dict(seed=g['seed'],n=len(gr),positive_n=sum(lab),negative_n=len(lab)-sum(lab),AUROC=point(values[0])))
        result['greedy_selection_sensitivity']=dict(replicates=greedy,valid_n=sum(g['AUROC'] is not None for g in greedy),AUROC_min_median_max=[float(v) for v in np.percentile([g['AUROC'] for g in greedy if g['AUROC'] is not None],[0,50,100])] if any(g['AUROC'] is not None for g in greedy) else None,not_a_confidence_interval=True);results.append(result)
        if i%20==0:print('Contour64 robustness conditions evaluated',i,'/',len(selections['analyses']),flush=True)
    save(T/'conservative_analyses.json',dict(created_at_utc=now(),metric='frozen primary contour64',original_ratings_unchanged=True,analyses=results,bootstrap_global_captions=caps,base_result_reproduced=abs(results[0]['AUROC']-.8785714285714284)<1e-12,no_secondary_metric_substitution=True))
    by={r['analysis_id']:r for r in results};b=by['all__pooled__binary__unrestricted'];baseline=b['AUROC'];uniform=[by['all__pooled__'+c+'__unrestricted']['AUROC'] for c in ['partial_as_same','partial_as_different']];save(T/'partial_target_sensitivity.json',dict(original_binary_AUROC=baseline,partial_as_same_AUROC=uniform[0],partial_as_different_AUROC=uniform[1],uniform_recoding_range=[min(uniform),max(uniform)],drop_from_original=[baseline-v for v in uniform],not_sharp_bounds_over_mixed_assignments=True,partial_judgments_never_changed=True,adjacent={c:by['all__pooled__'+c+'__unrestricted'] for c in ['same_vs_partial','partial_vs_different']}))
    repeat={r['repeat_id']:r['rating'] for r in read_json(D/'repeat_source_ratings.json')['pairs']};key=read_json(D/'repeat_hidden_key.json')['pairs'];old=np.array([rows[k['original_pair_id']]['rating'] for k in key]);new=np.array([repeat[k['repeat_id']] for k in key]);joined=[dict(**k,original_rating=int(a),repeat_rating=int(z) if str(z)!='U' else 'U',**{x:rows[k['original_pair_id']][x] for x in ['caption_left','caption_right','left_parent','right_parent','contour64','aspect_only']}) for k,a,z in zip(key,old,new)];freqcounts=Counter(r['rating'] for r in rows.values());samplecounts=Counter(old.tolist());freq=np.array([freqcounts[int(a)]/samplecounts[int(a)] for a in old]);unweighted=agreement(old,new,np.ones(len(key)));weighted=agreement(old,new,freq);repw=np.stack([counts[:,caps.index(r['caption_left'])]*counts[:,caps.index(r['caption_right'])] for r in joined],axis=1);exact_boot=np.full(5000,np.nan);ordinal_boot=np.full(5000,np.nan);weighted_boot=np.full(5000,np.nan);category={}
    known=np.isin(new,[0,1,2]);ordinal_scores=1-abs(old[known].astype(int)-new[known].astype(int))/2
    np.divide((repw*(old==new)).sum(1),repw.sum(1),out=exact_boot,where=repw.sum(1)>0);np.divide((repw[:,known]*ordinal_scores).sum(1),repw[:,known].sum(1),out=ordinal_boot,where=repw[:,known].sum(1)>0);rw=repw*freq;np.divide((rw*(old==new)).sum(1),rw.sum(1),out=weighted_boot,where=rw.sum(1)>0)
    for cat in [0,1,2]:
        mask=old==cat;den=repw[:,mask].sum(1);vals=np.full(5000,np.nan);np.divide((repw[:,mask]*(new[mask]==cat)).sum(1),den,out=vals,where=den>0);category[str(cat)]=dict(original_n=int(mask.sum()),retained_n=int((new[mask]==cat).sum()),retention=float((new[mask]==cat).mean()),repeat_counts=dict(Counter(str(z) for z in new[mask])),conditional_caption_bootstrap95=interval(vals),valid_bootstrap_n=int(np.isfinite(vals).sum()))
    save(T/'larger_repeatability.json',dict(n=len(key),sampling_original_counts={str(k):v for k,v in samplecounts.items()},original_corpus_counts={str(k):v for k,v in freqcounts.items()},repeat_counts=dict(Counter(str(z) for z in new)),sample_agreement=unweighted,original_category_reweighted_agreement=weighted,exact_caption_bootstrap95=interval(exact_boot),linear_ordinal_caption_bootstrap95=interval(ordinal_boot),reweighted_exact_caption_bootstrap95=interval(weighted_boot),category_stability=category,pairs=joined,not_independent_human_or_interrater_validation=True,limitations='Stratified repeat sample oversamples same judgments. All35 available same included,45 partial/different each. Changed IDs hide prior decisions but prior source exposure and same-session memory remain. Caption resampling does not erase rating bias.',original_ratings_unchanged=True))
    rerated=[]
    for label in ['original','repeat','stable_original_repeat']:
        eligible=[];labs=[];weights=[]
        for j,r in enumerate(joined):
            v=r['original_rating'] if label=='original' else r['repeat_rating']
            if v not in [0,2]:continue
            if label=='stable_original_repeat' and r['original_rating']!=r['repeat_rating']:continue
            eligible.append(dict(r,pair_id=r['original_pair_id']));labs.append(int(v==2));weights.append(freq[j])
        rerated.append(dict(label=label,unweighted=evaluate(eligible,labs,counts,caps),original_category_frequency_reweighted=evaluate(eligible,labs,counts,caps,weights)))
    save(T/'repeat_prediction_sensitivity.json',dict(results=rerated,not_replacement_of_original_labels=True,original_repeat_subset_selected_by_original_categories=True,source_corpus_generalization_not_independent=True))
    adequate_binary=[r for r in results if r['contrast']=='binary' and r['adequate_conditional_uncertainty']];drops=[dict(analysis_id=r['analysis_id'],drop=baseline-r['AUROC']) for r in adequate_binary if baseline-r['AUROC']>=.10];br=by['all__broad_random__binary__unrestricted'];am=by['all__aspect_matched__binary__unrestricted'];mixgap=abs(br['AUROC']-am['AUROC']);mixed_sensitive=mixgap>=.10 and min(br['contour_minus_aspect'],am['contour_minus_aspect'])<=0;uniform_sensitive=max(baseline-v for v in uniform)>=.10 or max(uniform)-min(uniform)>=.10;repeat_sensitive=any(category[str(cat)]['retention']<.80 for cat in [0,2]);ra={r['label']:r['unweighted'] for r in rerated};repeat_drop=ra['original']['AUROC']-ra['repeat']['AUROC'] if ra['original']['AUROC'] is not None and ra['repeat']['AUROC'] is not None else None;repeat_sensitive |= repeat_drop is not None and repeat_drop>=.10;core=[by['all__pooled__binary__parent'],by['extent_and_recovery_clean__pooled__binary__parent']];unsupported=all(r['adequate_conditional_uncertainty'] and (r['AUROC']<=.5 or r['caption_bootstrap95'][1]<=.5) for r in core);keysubset=[by[f'all__pooled__binary__{m}'] for m in ['parent','dyad','parent_dyad']]+[by['extent_and_recovery_clean__pooled__binary__parent']];qualifications=any(not r['adequate_conditional_uncertainty'] for r in keysubset) or category['1']['retention']<.80 or unweighted['exact']<.85 or any(by['all__pooled__'+c+'__unrestricted']['AUROC']<.65 or by['all__pooled__'+c+'__unrestricted']['caption_bootstrap95'][0]<=.5 for c in ['same_vs_partial','partial_vs_different']);sensitive=bool(drops or mixed_sensitive or uniform_sensitive or repeat_sensitive);status='unsupported under conservative analysis' if unsupported else 'sensitive to one or more evaluation assumptions' if sensitive else 'robust with important qualifications' if qualifications else 'robust'
    save(T/'DISPOSITION.json',dict(classification=status,rule=spec['interpretation'],unsupported_evidence=unsupported,adequate_binary_drops=drops,sampling_mixture_sensitive=bool(mixed_sensitive),stratum_gap=mixgap,uniform_partial_recoding_sensitive=bool(uniform_sensitive),repeat_category_or_prediction_sensitive=bool(repeat_sensitive),repeat_binary_AUROC_drop=repeat_drop,qualifications=bool(qualifications),frozen_Trial2_status_unchanged='supported within registered sample',not_a_new_validation_pass=True,no_downstream_assays=True))
    seal([p for p in T.glob('*.json')]+[D/'caption_bootstrap_draws.npz',OUT/'src/evaluate_dm2_robustness.py'],D/'ANALYSIS_SEAL.json');print('Contour64-only robustness results sealed; original evidence untouched',flush=True)
if __name__=='__main__':main()
