from inventory_v6_common import *
from collections import Counter,defaultdict
import numpy as np
def main():
    guard();verify_dependencies()
    for n in ['DIAGNOSIS_SEAL.json','DEVELOPMENT_AMENDMENT_SEAL.json','CANDIDATE_MODEL_SEAL.json','FRESH_SOURCE_SEAL.json','PAIR_DECISION_SEAL.json']:verify_seal(D/n)
    plan=read_json(D/'PLAN.json');train=read_json(D/'discovery_parents.json');fresh=read_json(D/'fresh_source_reference.json')['parents'];test=read_json(D/'fresh_assignments.json');bundle=read_json(D/'sealed_candidate_model.json');gates=[];accepted=[]
    pairkey=read_json(D/'pair_audit_hidden_key.json');judgments={p['pair_id']:p['judgment'] for p in read_json(D/'masked_native_pair_decisions.json')['nonmember_retrieval_pairs']}
    for c in bundle['whole_candidates']:
        rr=[r for r in test if r['candidate']==c['candidate_id'] and r['nominal_candidate_accepted'] and r['source_resolved']];stable=[r for r in rr if r['stable_candidate']==c['candidate_id']];ts=sum(r['threshold_class_stable'] for r in rr)/len(rr) if rr else None;ns=sum(r['alignment_class_stable'] for r in rr)/len(rr) if rr else None
        positives=[p for p in pairkey if p['candidate']==c['candidate_id'] and p['kind']=='positive'];positive_agreement=sum(judgments[p['pair_id']]=='same_whole_source_organization' for p in positives)/len(positives) if positives else None
        # Nonmember-to-nonmember gallery pairs are not candidate false-grouping
        # evidence. No accepted fresh prediction provides such a denominator.
        false_denominator=sum(r['nominal_candidate_accepted'] and r['source_resolved'] and r['candidate']==c['candidate_id'] for r in test)
        false_rate=None if false_denominator==0 else None
        results=dict(source_train_coherence=c['source_decision']=='retain_candidate',train_instances=c['training_instances']>=8,train_captions=c['training_captions']>=3,fresh_stable_instances=len(stable)>=5,fresh_caption_support=len({r['caption'] for r in stable})>=3,accepted_positive_pair_min=len(positives)>=10,positive_agreement=positive_agreement is not None and positive_agreement>=.85,false_grouping=false_rate is not None and false_denominator>=20 and false_rate<=.10,threshold_stability=ts is not None and ts>=.9,alignment_stability=ns is not None and ns>=.9)
        qualifies=all(results.values())
        if qualifies:accepted.append(c['candidate_id'])
        gates.append(dict(candidate_id=c['candidate_id'],train_instances=c['training_instances'],train_captions=c['training_captions'],source_decision=c['source_decision'],nominal_fresh_accepted=len(rr),stable_fresh=len(stable),stable_fresh_captions=len({r['caption'] for r in stable}),threshold_stability=ts,alignment_stability=ns,accepted_positive_pair_n=len(positives),positive_agreement=positive_agreement,false_grouping_rate=false_rate,false_grouping_denominator=false_denominator,gates=results,validated=qualifies,insufficient_audit_evidence='No accepted-positive fresh assignment exists for the retained candidate; formal positive/false-grouping rates are not estimable, not zero error. Source-rejected candidates were never assignable.'))
    assert not accepted,'Positive validation requires implementation of actual accepted-pair audit, not hard-coded defaults'
    qualification=read_json(D/'source_diagnosis_qualification.json');faint={r['parent_id'] for r in read_json(D/'source_unknown_diagnosis.json')['parents'] if 'insufficient_photographic_morphology' in r['overlapping_hypotheses']};assignments=[]
    for r in train:
        if r['parent_boundary_status']=='competing_join':state='unresolved_compound_or_contact'
        elif r['parent_id'] in faint or r['diagnosis_stage']=='insufficient_photo_or_disconnected':state='insufficient_photographic_morphology'
        elif r['structural_class']!='UNK':state='source_resolved_existing_V3'
        else:state='source_confirmed_writing_V3_UNK'
        assignments.append(dict(parent_id=r['parent_id'],caption=r['caption'],row_id=r['row_id'],native_source=r['native_source'],native_bbox=r['native_bbox'],source_objects=r['source_objects'],retained_v3_class=r['structural_class'],new_validated_class=None,expanded_structural_class=r['structural_class'],source_state=state,whole_connected_parent_primary=True,original_parent_status=r['parent_boundary_status'],validated_composition=None))
    bycap=defaultdict(list)
    for r in train:bycap[r['caption']].append(r)
    rng=np.random.default_rng(20261011);caps=sorted(bycap);rates=[]
    for _ in range(2000):
        rr=[r for cap in rng.choice(caps,len(caps),replace=True) for r in bycap[cap]];rates.append(sum(r['structural_class']!='UNK' for r in rr)/len(rr))
    composition=read_json(T/'composition_robustness_and_controls.json');known=sum(r['structural_class']!='UNK' for r in train);unk=len(train)-known;fw=[r for r in test if r['source_membership']=='confirmed_writing']
    summary=dict(created_at_utc=now(),discovery_parents=len(train),existing_v3_assigned=known,v3_only_coverage=known/len(train),v3_plus_validated_coverage=known/len(train),coverage_delta=0,caption_bootstrap95=np.percentile(rates,[2.5,97.5]).tolist(),validated_new_classes=[],validated_compositional_classes=[],validated_factor_coverage=0,unknown_confirmed_parents=unk,unknown_confirmed_rate=unk/len(train),exclusive_source_states=dict(Counter(r['source_state'] for r in assignments)),all_competing_contacts=sum(r['parent_boundary_status']=='competing_join' for r in train),known_v3_with_competing_contact=sum(r['parent_boundary_status']=='competing_join' and r['structural_class']!='UNK' for r in train),source_observed_variant_hypotheses=len(qualification['native_likely_V3_family_variants']),fresh=dict(proposals=len(fresh),confirmed_writing=len(fw),confirmed_nonwriting=sum(r['membership']=='confirmed_nonwriting' for r in fresh),unresolved_membership=sum(r['membership']=='unresolved' for r in fresh),resolved_parent_writing=sum(r['source_parent_status']=='confirmed_connected_writing_trace' for r in fresh),v3_only_assigned=sum(r['v3_class']!='UNK' for r in fw),v3_plus_validated_assigned=sum(r['v3_class']!='UNK' for r in fw),new_stable_accepted=0,captions=3,writing_coverage=sum(r['v3_class']!='UNK' for r in fw)/len(fw)),composition_diagnostics=composition['summary'],interpretation='No defensible inventory expansion passed this source-only workflow. This does not establish that the remaining parents lack recurrent forms or are irreducibly ambiguous. Raster representation, small caption sample, source contacts and morphology boundaries remain limitations.',sequences_constructed_before_inventory_freeze=False,prior_taxonomies_retuned=False)
    save(T/'candidate_validation.json',dict(candidates=gates,validated_new_classes=accepted,all_gates_predeclared=True));save(T/'structural_coverage.json',summary);save(F/'expanded_parent_assignments.json',assignments);save(F/'structural_inventory.json',dict(created_at_utc=now(),v3_model_sha256=sha256(MODEL),base_inventory='Immutable V3 core classes; ST09 exclusion unchanged',validated_new_classes=accepted,validated_compositional_classes=[],candidates=bundle['whole_candidates'],failed_candidates_preserved=True,membership='Immutable V5 source reference, not re-adjudicated',abstention='Preserve V5 UNK and unresolved contacts; no validated new class to replace them',sequence_stage='Must run only after V6 FREEZE_MANIFEST exists'))
    print('V6 prefreeze source states',summary['exclusive_source_states'],'coverage',known,'/',len(train),'fresh V3',summary['fresh']['v3_only_assigned'],'/66; validated additions0',flush=True)
if __name__=='__main__':main()
