"""Direct native-source judgments. No transcription or assay input is read."""
from common import OUT,read_json,write_json,sha256
from datetime import datetime,timezone

# Native row body seeds are manual source observations, not automatic density peaks.
# Seed y is the approximate lower body edge; connected upper ink is recovered whole.
# Other visible row seeds prevent ownership by a neighboring body band.
REVIEWS={
 'V_042':dict(seed_y=1513,body=30,x_extent=[375,1940],other_rows=[1368,1435,1590],exclude=[],note='Candidate combines two body rows. Lower row is writing across a dark substrate stain; paired tall uprights continue into lower horizontal/return traces. Frame topology is visible; order/pen lifts unknown.',local=['writing: paired tall uprights with lower connecting trace; preserve connected whole','writing: paired uprights and lower open return; above-row ink remains other ownership','writing: tall paired structure beside stain; upper contact uncertain','writing: paired structure and adjacent detached return; do not infer a single grapheme']),
 'V_017':dict(seed_y=1204,body=30,x_extent=[610,2055],other_rows=[1043,1124],exclude=[[1610,1050,1780,1270]],note='Two rows and a plant branch are merged. Plant stem/pods are drawing. Target lower body has separate left/right writing fields around plant; row continuation across drawing retained as uncertain.',local=['mixed writing and plant pod/branch: drawing region excluded; writing remainder separate','drawing: forked plant stem, not a writing unit','writing: closed double-lobed trace; internal split unknown','writing: similar closed double-lobed trace, separate from plant']),
 'V_007':dict(seed_y=895,seed_slope=.014,body=28,x_extent=[745,2450],other_rows=[788,841,969],exclude=[[1910,740,2035,1000]],note='Body rows are distinct; plant stem divides writing flow. Tall connected assemblies retained by lower body contact, not by bounding-box center. Final right writing extends beyond old bbox.',local=['writing: tall uprights over lower connected frame; whole assembly hypothesis','writing: narrow return/terminal trace; adjacent row tail ownership unknown','writing: lobed trace and long descending return; lower continuation visible','writing: small lobed closed trace, no photograph evidence for internal pen lifts']),
 'V_032':dict(seed_y=861,body=32,x_extent=[405,1590],other_rows=[693,776,951],exclude=[[1595,630,2300,990]],note='Plant twigs, leaves and red buds occupy the old right half. Target lower writing body ends before plant; separate short upper row is not part of it.',local=['drawing: leaves/buds/stem, with nearby writing outside exclusion edge','drawing: red buds on thin branch, not writing','drawing: buds/leaf and long plant return','drawing: red buds/branch, not a written frame']),
 'V_015':dict(seed_y=1334,body=30,x_extent=[585,1315],other_rows=[1248,1410,1460],exclude=[[1320,1158,2200,1470]],note='Blue-green flower disks and radiating petals are drawing. Target middle writing row ends before first flower; upper/lower rows remain distinct.',local=['drawing: blue-green disk with radiating petals','drawing: petal edge around disk','writing: paired tall uprights and lower connector; connected assembly retained','writing: descending open return, not flower decoration']),
 'V_033':dict(seed_y=718,seed_slope=.04,body=27,x_extent=[575,1620],other_rows=[626,793],exclude=[[1640,540,2670,830]],note='Large blue serrated leaf is drawing. Two candidate body rows are disentangled; target middle row slopes downward across the capture and includes high paired structures with connected lower traces.',local=['writing: paired tall stems and lower connector','writing: tall hooked upright joined to lower loop; atomicity unknown','writing: small closed return with adjoining trace','writing: small open return; upper row context separate']),
 'V_027':dict(seed_y=917,seed_slope=.04,body=29,x_extent=[908,1270],other_rows=[759,842],exclude=[],note='The old row combines a long upper row and short final lower row. Lower final row is a short writing field sloping down to right and ending well before the large plant.',local=['writing: lower-row hooked upright joined to circular return','writing: upper-row hooked upright; belongs to different row','writing: lower-row paired uprights, retain connected assembly','writing: small upper-row trace; not lower-row group']),
 'V_025':dict(seed_y=2396,seed_slope=-.005,body=31,x_extent=[785,2500],other_rows=[2237,2329,2510],exclude=[[1830,2150,2020,2560]],note='Red vertical plant stem is drawing and splits left/right writing fields. Candidate mixes successive body rows. Source-recomposed review corrects a too-low initial seed; lower fields have distinct wide visible gaps and uncertain continuation across plant.',local=['writing: lower-row paired uprights near upper-row descending trace; contact ownership unknown','drawing: long red plant stem','writing: small angular trace in right writing field','writing: descending curved return in left field']),
 'V_045':dict(seed_y=1218,body=30,x_extent=[735,1840],other_rows=[1134,1326],exclude=[[1840,1020,2250,1360],[1150,1270,1690,1400]],note='Target middle row is writing; neighboring tall ascenders belong to different body rows. Recomposed source review corrects a too-low initial seed. Large green flower below and leaf stems right are drawing.',local=['writing: long descending return near other-row tall top; ownership ambiguous at crossing','writing: paired uprights over connected low return','writing: double-lobed closed trace','writing: descending hooked return with neighboring lobed trace']),
 'V_019':dict(seed_y=1337,seed_slope=-.01,body=28,x_extent=[550,2340],other_rows=[1155,1239,1415],exclude=[[890,1100,1340,1440],[1880,1330,2030,1450]],primary_eligible=False,note='Plant leaves/stems are drawing. Left/right lower writing fields have differing baselines; continuation and a single complete physical row are unknown, so excluded from primary endpoints.',local=['writing: tall compound with looped crossbar and lower frame; internal split unknown','writing: paired uprights with joined upper loop and lower return','writing: closed lobed trace in lower right field','drawing: pointed green leaf edge, not a written stem']),
 'V_044':dict(seed_y=886,body=29,x_extent=[312,890],other_rows=[729,811],exclude=[[1460,720,1730,980]],note='Candidate combines long upper body and short lower final row. Lower final row ends around x890; blue disk belongs to drawing beside upper row and is excluded.',local=['drawing: blue flower disk and surrounding petals','writing: lower-row paired uprights; upper row separate','writing: upper-row paired uprights, not lower final row','writing: upper-row hooked upright, not lower final row']),
 'V_004':dict(seed_y=2276,body=28,x_extent=[570,2610],other_rows=[2179,2335],exclude=[[0,2100,390,2380]],primary_eligible=False,note='Very faint lower row, with dark writing clearer on left and uncertain right extent/ghost traces. Margin pits are nonwriting. Writing is retained, but complete membership and right endpoint are unknown.',local=['writing: tall uprights joined through lower connecting trace','nonwriting: isolated substrate pits/stain, no writing shape','writing: faint tall paired trace; closure/contact unknown at this contrast','writing or show-through: faint angular trace, unresolved row ownership']),
 'V_070':dict(seed_y=2740,body=27,x_extent=[478,1375],other_rows=[2599,2662],exclude=[[1710,2500,1780,2830]],note='Short final lower row is distinct from long preceding row. Faint writing on colored substrate remains visible; red vertical plant stem lies outside final row.',local=['writing: rounded closed loop on tinted substrate','writing: upper-row paired upright top, not final-row body','writing: faint final-row paired upright/lower return','writing: connected low horizontal/open-return sequence; unit count unknown']),
 'V_071':dict(seed_y=651,seed_slope=.015,body=27,x_extent=[835,1640],other_rows=[735],exclude=[[1640,480,2790,730]],note='Clear writing row before large green leaf. Old boundary extends into leaf edge; leaf outline/color excluded. High paired construction belongs to body row below it.',local=['writing: tall paired uprights connected to lower trace','drawing: green leaf edge, not part of writing','writing: short open return/angular trace','writing: small rounded loop in low body']),
 'V_075':dict(seed_y=974,body=29,x_extent=[854,1640],other_rows=[808,885,1057],exclude=[[1640,760,2660,1085]],note='Candidate spans upper and lower writing bodies plus green leaf. Lower target ends before leaf; stacked tall forms from neighboring rows can touch and stay unknown if ownership is shared.',local=['writing: vertically neighboring paired tall assemblies, shared contact unresolved','writing: upper-row low sequence with lower-row tall top nearby','writing: target lower-row paired uprights','writing: upper-row paired construction; separate body owner']),
 'V_073':dict(seed_y=1623,body=29,x_extent=[1910,2310],other_rows=[1532],exclude=[[1200,1460,1920,1750]],note='Lower right short row contains writing; plant leaves occupy left old group. Physical body row ends before right blank parchment.',local=['writing: tall paired uprights connected to lower horizontal trace','writing: small loop in lower row','drawing: green leaf outline/interior','mixed drawing edge and adjacent writing return; writing kept separately, contact unknown']),
 'V_060':dict(seed_y=691,seed_slope=.025,body=29,x_extent=[390,2095],other_rows=[572,755],exclude=[],note='Target middle row slopes down to right and is writing, not plant. Candidate includes tops from lower row. Pale small detached traces above body are retained as membership-unknown unless visibly continuous.',local=['writing: paired uprights over lower bench-like connector','writing: target paired tall trace with attached lower body','writing: paired upright form, upper closure visible','writing: low double-lobed closed trace']),
 'V_086':dict(seed_y=908,seed_slope=-.015,body=28,x_extent=[350,2320],other_rows=[752,831,982],exclude=[],note='Two dense body rows are merged. Target lower row has a long descending return from preceding row crossing toward it; contact ownership unknown. Red isolated stain is nonwriting.',local=['writing: upper-row descending return near lower-row loop, contact uncertain','writing: adjacent upper/lower tall structures must retain separate owners','writing: target paired upright with horizontal top','writing: upper-row descending curve reaching lower body; shared ownership unknown']),
 'V_057':dict(seed_y=723,body=27,x_extent=[914,1495],other_rows=[577,647,797],exclude=[],note='Short lower final row distinct from long upper row. Low horizontal connected traces are writing; upper-row groups to the right are not in this row.',local=['writing: lower-row open return with long descending curve','writing: lower-row closed lobed trace','writing: lower-row connected horizontal and open-return assembly','writing: upper-row connected horizontal/return trace; different row owner']),
 'V_085':dict(seed_y=715,body=29,x_extent=[937,2605],other_rows=[552,788],exclude=[[1930,497,2150,785]],note='Long target writing row lies around a pale plant stem. Narrow straight line at left is drawing or substrate trace, not a reusable writing assembly; connected tall structures remain writing.',local=['writing: tall compound with joined loop and low connector','nonwriting or drawing: long thin vertical trace without body construction','writing: very tall paired uprights with lower open return','writing: hooked low angular trace; small detached upper mark unresolved']),
 'V_104':dict(seed_y=674,body=29,x_extent=[360,2115],other_rows=[490,578,751],exclude=[[1620,500,1895,780]],note='Candidate merges two body rows and blue flowering/seed-pod drawing. Lower writing fields remain on either side; pod outlines excluded, uncertain contacts at plant edge retained.',local=['drawing: blue pod and radiating spikes, not a writing assembly','writing: lower-row paired tall construction','drawing: blue bud and spikes','writing: hooked upright joined to a lower open return']),
 'V_095':dict(seed_y=3022,seed_slope=-.018,body=28,x_extent=[760,1725],other_rows=[2862,2944],exclude=[[1760,2800,2030,3150]],note='Candidate merges short final lower-left writing row, upper-right writing and green/red plant. Target final lower-left row ends before plant; upper-right text is a different physical body row.',local=['writing: paired tall uprights connected to lower return','drawing: green vertical plant stem','writing or substrate tint: small round trace on green stain, retain ambiguous membership','writing: upper-right closed lobed trace, different row']),
 'V_103':dict(seed_y=933,seed_slope=-.007,body=28,x_extent=[935,2705],other_rows=[786,856,1007],exclude=[[1940,720,2220,1050]],note='Lower left and right writing fields share a body level around branching plant. Old candidate retains only right and mixes upper row. Blue disks/thin stems excluded; physical continuation is not logical reading.',local=['writing: two neighboring rows with tall tops; separate body ownership','writing: upper descending terminal loop near lower row, contact unknown','writing: lower closed lobed trace','writing: lower tall pair joined to short horizontal return']),
 'V_082':dict(seed_y=425,body=27,x_extent=[355,2310],other_rows=[333,485],exclude=[],uncertain_zones=[[1050,270,1480,530],[1520,310,1605,485]],primary_eligible=False,note='Writing bodies are distinct, but severe smear/overwriting and faint traces in middle prevent complete membership and boundary decisions. Dark diagonal material is not safely assignable as drawing or writing.',local=['writing or show-through: narrow faint vertical stroke, ownership unknown','unknown: dark smear with diagonal/overwritten traces, no valid assembly boundary','writing: faint open return/angular body','writing: pale tall paired construction; internal contact unresolved']),
 'V_144':dict(seed_y=3028,body=27,x_extent=[475,1965],other_rows=[2899,2958,3086],exclude=[[0,2800,465,3150]],note='Human head/green bath outline on left is drawing. Lower target row starts to its right and is distinct from upper and short final rows; long descenders may share raster contact.',local=['writing: lower-row paired upright below upper closed loop; contact unresolved','writing: closed double-lobed lower-body trace','writing: closed lobed trace with descending terminal return','writing: hooked upright joined to rounded return']),
 'V_142':dict(seed_y=2882,body=29,x_extent=[371,1285],other_rows=[2710,2804,2960,3032],exclude=[[1285,2640,2350,3070]],note='Bathing figures/green vessel are drawing. Target middle writing row ends before figure. Old candidate combines successive body rows and drawing shoulder.',local=['writing: upper/lower glyph contact through descending stroke, ownership unknown','writing: tall paired construction connected to lower body','writing: hooked upright with circular return, following paired stem separate hypothesis','writing: low double-lobed trace with descending return']),
 'V_138':dict(seed_y=1650,seed_slope=-.003,body=26,x_extent=[355,2330],other_rows=[1486,1538,1594,1705,1769],exclude=[[0,1490,330,1630]],note='Dense writing, with several distinct body rows inside old one. Connected vertical descenders touch subsequent tall/frame structures. Shared contact components remain unknown rather than split by skeleton necks.',local=['writing: upper-row hooked/tall trace touching next row frame; owner ambiguous','writing: multirow vertical contact and frame; preserve alternatives','writing: target frame/inserted-tall-like assembly, continuity visible but atomicity unknown','writing: long upper-row return reaches lower row; ownership cannot be forced']),
 'V_149':dict(seed_y=1409,seed_slope=-.006,body=28,x_extent=[965,2490],other_rows=[1239,1300,1358,1469,1530],exclude=[],note='Several dense writing rows are merged; target lower body distinct. Long descending returns and high inserted/tall frame-like structures frequently touch neighboring rows; ambiguous connected ownership stays unknown.',local=['writing: upper frame and descending return reach lower construction; multirole contact unresolved','writing: long upper descending curve near lower horizontal trace, ownership unknown','writing: hooked upright/frame over lower return, neighbor-row overlap','writing: terminal descending curve into next row; pen lift/order unknown']),
 'V_146':dict(seed_y=960,seed_slope=-.005,body=27,x_extent=[270,2180],other_rows=[785,845,906,1019,1076],exclude=[],note='Several dense writing bodies within old candidate. Target lower body is distinct; long hooked uprights and descending curves cause multirow connected components, retained with unknown owners.',local=['writing: long multirow contact spanning hooked upright and low frame; cannot assign a single owner','writing: upper tall compound touches lower paired trace; ownership unknown','writing: upper-row frame linked toward lower loop; atomicity unknown','writing: tall hooked construction adjoining next-row trace; pen order unresolved']),
 'V_143':dict(seed_y=1248,seed_slope=-.006,body=28,x_extent=[1025,2605],other_rows=[1082,1140,1200,1310,1370],exclude=[],note='Dense writing panel at right; candidate mixes several adjacent body rows. Target lower body selected by source y and tall forms recovered whole only with unambiguous body ownership.',local=['writing: lower tall pair adjacent to upper descending return; contact unresolved','writing: hooked upright joined to circle and long descent, multiple rows involved','writing: connected low frame with taller insertion-like strokes; one assembly hypothesis','writing: paired uprights over horizontal low trace; visible continuous ink']),
 'V_156':dict(seed_y=1431,seed_slope=.006,body=27,x_extent=[330,2180],other_rows=[1289,1366,1481],exclude=[],note='Three writing body rows visible; lower target row retains high paired structures. Tiny detached marks between rows have uncertain ownership; old row combined upper and lower bodies.',local=['writing: lower paired structure beneath upper descending return; contact unknown','writing: paired tall lower structure below rounded upper stroke','writing: lower paired uprights with adjacent upper descending trace','writing: hooked tall construction contacting lower circle; ownership unknown']),
 'V_140':dict(seed_y=1019,seed_slope=-.008,body=28,x_extent=[420,2160],other_rows=[849,902,957,1080,1135],exclude=[[0,800,405,1170],[2160,800,2440,1170]],note='Blue vessel/water outline left and thin drainage lines right are drawing. Target dense writing row lies between these fields; row-crossing descenders stay ambiguous.',local=['writing: hooked tall upright with descender toward next row','writing: hooked tall upright joined to rounded trace and descending curve','writing: paired upright below previous-row loop; contact ownership unknown','writing: connected low horizontal return sequence; internal unit boundary unknown']),
 'V_154':dict(seed_y=1106,seed_slope=-.004,body=27,x_extent=[265,2335],other_rows=[925,987,1050,1170,1232],exclude=[],note='Dense writing body rows are distinct; old bbox clips true left start and mixes tall constructions from several rows. Source full-width review recovers left writing extent.',local=['writing: lower paired tall trace touches upper lobed return; owner unknown','writing: upper descending return reaches next row construction','writing: hooked upright with descender into lower frame; multirole ownership unknown','writing: descending curved return over next body row']),
 'V_110':dict(seed_y=774,seed_slope=.008,body=28,x_extent=[310,1995],other_rows=[629,699,842],exclude=[[0,570,260,900]],note='Body rows distinct; target middle-lower writing ends before old right bbox. Left vessel/figure outline is drawing. Green substrate stain near left glyphs is not a separable written sign.',local=['unknown: writing over green stain, boundary obscured; stain is not an assembly','writing: upright/descender spans neighboring body rows; owner unknown','writing: hooked high construction with lower closed loop','writing: paired tall trace with connected low return']),
 'V_117':dict(seed_y=2383,seed_slope=-.018,body=28,x_extent=[945,2650],other_rows=[2198,2270,2328,2440,2530],exclude=[],note='Pale dense writing, several body rows inside candidate. Target lower row has paired tall traces; vertically stacked assemblies sometimes touch and remain unassigned to a single row.',local=['writing: upper/lower paired constructions visibly stacked; contact owner unknown','writing: tall hooked upright overlaps lower paired construction','writing: lower paired uprights and adjacent descending return','writing: vertically stacked paired traces with probable contact; atomicity unresolved']),
 'V_187':dict(seed_y=2102,seed_slope=-.005,body=28,x_extent=[540,2495],other_rows=[1930,1985,2048,2160,2220],exclude=[[0,1870,530,2240],[2580,1870,2744,2240]],note='Red-centered margin stars and their connecting marginal curves are decoration. Main lower writing body remains distinct from upper row; ornament is not a group or writing-unit instance.',local=['decoration: red-centered margin star and connecting curve','decoration: right margin star, separate from text','writing: hooked upright descends toward next body row; owner unknown','writing: hooked upright/circular return and downward extension']),
 'V_196':dict(seed_y=1342,seed_slope=-.01,body=27,x_extent=[335,2250],other_rows=[1208,1274,1390,1450],exclude=[[0,1150,315,1470]],note='Two dense writing bodies merged; margin stars/curves excluded. Target lower body extends slightly beyond old right bbox; high constructions with shared upper contacts remain unknown.',local=['writing: upper-row tall frame/low connection; not target lower body','writing: hooked upright crosses toward lower tall pair, ownership unknown','writing: lower paired tall trace with adjacent descending return','writing: vertically adjacent paired traces, shared ink ownership unresolved']),
 'V_169':dict(seed_y=425,body=28,x_extent=[800,2635],other_rows=[359,491],exclude=[[1780,190,1955,600],[2030,190,2140,600],[2260,190,2470,600]],note='Red berries and connecting stems are drawing. Lower target writing remains in several separated fields. Where drawing touches a written trace, the boundary/membership stays unknown instead of reconstructing through the berry.',local=['drawing: red berry and plant stem, nearby writing separate','writing: vertically adjacent paired structures; separate owners or unknown contact','drawing: red berry with outline, not closed writing loop','drawing: red berry with stem']),
 'V_195':dict(seed_y=2095,seed_slope=-.006,body=27,x_extent=[665,2460],other_rows=[1959,2026,2152,2210],exclude=[[0,1900,645,2250],[2580,1900,2649,2250]],note='Dense writing with margin stars. Several body rows mixed in candidate; target lower body includes tall paired assemblies and detached small marks with unresolved owner.',local=['writing: tall paired frame-like assembly with lower connection','writing: hooked upright descends toward lower trace; owner uncertain','writing: hooked upright plus neighboring tall assembly, internal/contact alternatives','writing: neighboring tall forms from adjacent rows, no forced ownership']),
 'V_193':dict(seed_y=2003,seed_slope=.012,body=29,x_extent=[535,2400],other_rows=[1845,1920,2080,2150],exclude=[[0,1770,515,2180],[2570,1770,2689,2180]],uncertain_zones=[[600,1950,740,2070]],note='Three writing bodies mixed. Margin stars are decoration; round translucent substrate feature obscures part of lower writing. Its circular edge is not a reusable written unit.',local=['writing: hooked upright descends into next body, ambiguous owner','writing: target paired upright connected to lower trace','writing: upper descending curve over lower paired tall form, contact unresolved','writing: target paired uprights with low return; keep connected assembly']),
 'V_168':dict(seed_y=1421,body=28,x_extent=[389,1068],other_rows=[1340,1494],exclude=[[1080,1210,2550,1530]],uncertain_zones=[[685,1300,1080,1450]],note='Short writing row overlaps pale painted leaf, with large green leaf to right. Clear low writing remains; leaf edges excluded as drawing, overlapping faint ink stays unknown.',local=['writing: high structure with horizontal lower frame trace','mixed writing over pale leaf; loop itself writing, contact/drawing membership unknown','writing: paired tall uprights on pale colored substrate','writing: descending curved return in target body']),
 'V_157':dict(seed_y=2733,body=27,x_extent=[5555,7335],other_rows=[2560,2638,2798,2860],exclude=[[0,2500,5400,2880]],note='Right-hand rectangular writing field in a very wide foldout is distinct from circular fields to left. Candidate merges successive body rows; native crop preserves small high connected structures. Physical crease/panel identity remains separately adjudicated.',local=['writing: paired high frame with lower connector, retained whole','writing: upright and long descending stroke near next body; owner unknown','writing: hooked upright descends into next row, shared contact unknown','writing: paired uprights joined to low trace; not detached decoration']),
 'V_191':dict(seed_y=835,body=28,x_extent=[520,1900],other_rows=[687,761,912,976],exclude=[[0,630,500,990],[2580,630,2670,990]],note='Margin star/curve is decoration. Candidate mixes paragraph bodies; middle target is a shorter writing row before following full row. Right endpoint requires recomposed source review before pixel normalization.',local=['decoration: margin star and curving tail','writing: paired upright and connected low horizontal trace','writing: upper low return touching target tall pair; owner unknown','writing: hooked upright descending toward following row; cannot assign by bbox']),
 'V_189':dict(seed_y=2068,body=28,x_extent=[437,2440],other_rows=[1928,1996,2143,2208],exclude=[[0,1880,415,2240]],note='Target lower full writing row distinct from upper and following short paragraph row. Red margin star and curve excluded. Tall/descender contacts among adjacent rows remain unknown.',local=['writing: target paired uprights with low connector','writing: neighboring row tall-frame contact with long cross-trace; ownership unknown','writing: paired tall structure below upper descending return','writing: long descending curve crosses toward next row; owner unknown']),
 'V_202':dict(seed_y=1553,body=29,x_extent=[246,2235],other_rows=[1435,1481,1632,1700],exclude=[[0,1350,230,1720]],note='Main long target writing row lies beneath short prior row and above next full row. Margin star and right substrate tear are nonwriting; high connected constructions remain writing.',local=['writing: tall frame-like structure with connected low frame/return','writing: high paired trace joined to low horizontal/loop construction','writing: high paired construction followed by connected low repeated returns','writing: low recurrent connected loops/returns; internal segmentation alternatives retained']),
 'V_188':dict(seed_y=2645,seed_slope=-.01,body=28,x_extent=[388,2440],other_rows=[2413,2481,2560,2720,2790],exclude=[[0,2350,370,2820]],note='Three dense writing bodies combined; target lower body has unusually tall connected constructions. Margin star/curve excluded; vertically continuous shared components keep unknown ownership.',local=['writing: vertically joined tall frame structures spanning rows, owner unresolved','writing: paired tall lower structure beneath upper loop','writing: target paired tall uprights and connected lower return','writing: tall hooked upright joined to elongated low return; owner source-specific']),
 'V_185':dict(seed_y=1291,body=28,x_extent=[650,2490],other_rows=[1087,1154,1231,1360,1435],exclude=[[0,1030,635,1470]],note='Dense writing bodies and margin stars. Target lower body differs from upper bodies in old candidate; long descenders bridge rows and stay unknown rather than becoming compound unit IDs.',local=['writing: multirow vertical assembly spanning hooked uprights and frames; owner unknown','writing: hooked upright with descending curve reaching lower body','writing: upper hooked upright meets lower paired construction; ownership unknown','writing: hooked upright and long descending return toward next row']),
}

def main():
    root=OUT/'data/observations/source_adjudication_v2';q=read_json(root/'queue_plan.json');rows=[];local=[]
    for case in q['selected_rows']:
        vid=case['view_id']
        if vid not in REVIEWS:continue
        r=REVIEWS[vid];rows.append(dict(case,**{k:v for k,v in r.items() if k!='local'},status='source_reviewed: row correction with explicit residual unknowns',review_basis='Full native-width context and four unscaled native local crops; conventional forms hidden',pen_lift='unknown',logical_reading_direction='unknown',reviewer='Codex source image inspection',reviewed_at_utc=datetime.now(timezone.utc).isoformat()))
        cases=[c for c in q['selected_local_assemblies'] if c['view_id']==vid]
        for case,note in zip(cases,r['local']):local.append(dict(case,status='source_reviewed',observation=note,pen_lift='unknown',stroke_order='unknown',grapheme_atomicity='unknown'))
    write_json(root/'row_judgments.json',rows);write_json(root/'assembly_judgments.json',local)
    write_json(root/'adjudication_progress.json',dict(reviewed_rows=len(rows),selected_rows=len(q['selected_rows']),reviewed_assemblies=len(local),selected_assemblies=len(q['selected_local_assemblies']),source_script_sha256=sha256(OUT/'src/record_source_adjudication_v2.py')))
    print('Recorded',len(rows),'rows and',len(local),'local cases',flush=True)

if __name__=='__main__':main()
