"""Source judgments for curved/radial writing and visible capture panels."""
from common import OUT,read_json,write_json

CURVES={
 'V_115':dict(observation='Four concentric writing bands surround central radial writing labels and heads. Thin ring rules, head outlines and central flower are drawing. Native crops show paired tall/low connected traces and small detached marks; no pen lift/order or arbitrary ring seam is certified.',writing_paths='four annular bands plus separate radial labels',visible_panel_fractions=[],orientation='tangential assemblies with ascenders outward in inspected ring sectors; logical order/seam unknown'),
 'V_122':dict(observation='Two diagram fields divided by a vertical crease. Left outer dark bands and inner radial labels are writing; right red outer band and brown internal strings are also writing. Stars, colored rays, dividing rules and face discs are drawing. Red writing must not be rejected by brown-ink color assumptions.',writing_paths='left concentric bands/radial labels; right red annular band and interior/radial strings; separate straight paragraphs',visible_panel_fractions=[.51],orientation='ring sectors follow tangent; interior/radial orientations vary; reading order unknown'),
 'V_123':dict(observation='Left sparse radial writing fields around central device; right outer cell-ring strings and radial strings around face. Gold/green stars, cell dividers and central face rays are drawing. Cell divider boxes cannot be promoted to bench/frame writing units.',writing_paths='right annular cell-ring and radial labels; left separate rotated labels',visible_panel_fractions=[.50],orientation='multiple tangential/radial orientations, no common straight-line x endpoint'),
 'V_124':dict(observation='Wide capture has left/central star-label fields and right circular field with perimeter and radial writing. Stars/faces and thin radial rules are drawing. Native crops show continuous written strings, with small isolated labels separate from stars. Visible vertical creases partition capture areas, while circle writing crosses a crease.',writing_paths='right annular band and radial strings; left/central isolated labels and straight paragraphs',visible_panel_fractions=[.31,.565,.805],orientation='tangential ring and rotated radial labels; no known ring seam'),
 'V_125':dict(observation='Left spiral/curved band field, central seven-lobed blue shape with annular writing and right sun field with curved strings. Blue disks/rays, stars and rules are drawing. Native crops distinguish strings beside rings from the oval/star ornament outlines.',writing_paths='left curved/spiral bands and paragraph; central/right annular bands and interior labels',visible_panel_fractions=[.19,.435,.69],orientation='local tangent orientations change around curved/spiral bands; starting seams unknown'),
 'V_126':dict(observation='Single main circular field has outer annular writing, inner annular writing and radial strings between blue/green spokes. Colored spokes, small oval nodes and central star are drawing. Native crops show short strings and separated upper marks, which do not resolve pen order.',writing_paths='outer/inner annular bands plus radial writing and top paragraph',visible_panel_fractions=[],orientation='tangential ring sectors and inward/outward radial strings; common logical order unknown'),
 'V_127':dict(observation='Wide capture contains three circular fields and right rectangular paragraph. Brown strings around each field and inside central rings are writing; blue/green structures, face/ray outlines, rules and stippling are drawing. Highest-native samples distinguish tall/frame-like constructions from ring rules.',writing_paths='three sets of annular/radial bands plus separate right paragraph',visible_panel_fractions=[.34,.605,.84],orientation='independent circular field tangents and paragraph x; no common ring seam'),
 'V_128':dict(observation='Circular field with figures in containers, stars and two central animals. Outer and inner annular strings and separate figure labels are writing. Figure/container crosshatching, stars and ring rules are drawing. A vertical crease traverses left ring sectors without establishing a group boundary.',writing_paths='outer/inner annular strings and figure labels',visible_panel_fractions=[.37],orientation='tangential writing with local high strokes outside body; radial labels vary'),
 'V_129':dict(observation='Separate circular field with central animal and figure labels. Outer/inner annular writing distinct from animal/figure outlines, tub crosshatching and stars. Native gaps visible locally; photo does not establish matching panel identity with V128.',writing_paths='outer/inner annular bands plus figure/center labels',visible_panel_fractions=[],orientation='tangential writing and rotated labels, seam unknown'),
 'V_130':dict(observation='Main circular field has outer and inner strings, centered animal label and separate figure labels. Red/green/blue figure details, animal contour, stars and faint circle rules are drawing. Native crops retain tall connected forms within writing strings.',writing_paths='outer/inner annular bands and rotated figure/center labels',visible_panel_fractions=[],orientation='local tangent/radial orientations; common logical reading order unknown'),
 'V_131':dict(observation='Wide foldout has four separate circular fields. Left/second fields have clearer annular writing; right fields are very faint and contacts are often undecidable. Figures/stars/animals and container decoration are drawing. Panel creases do not imply text seams.',writing_paths='four annular/radial field sets, some severely faint',visible_panel_fractions=[.27,.485,.70],orientation='separate local circular orientations; no common seam or straight x endpoint'),
 'V_132':dict(observation='Two faint circular fields in one capture. Native inspection separates some continuous strings from bodies/heads/star outlines; heavily faded sectors retain unknown membership and boundaries. Visible vertical fold runs through left circle and another divides the fields.',writing_paths='two faint annular/radial writing field sets',visible_panel_fractions=[.25,.59],orientation='tangential ring sectors, rotated figure labels; completeness unknown'),
 'V_133':dict(observation='Annular writing and figure labels surround a central vessel/device. Large physical hole removes substrate at right-middle; missing ink there is unknown and cannot be treated as a whitespace group boundary. Figures, stars and device lines are drawing.',writing_paths='annular bands and separate figure/center labels, interrupted by hole',visible_panel_fractions=[],orientation='tangential/radial local forms; hole interrupts any complete inventory'),
 'V_134':dict(observation='Writing follows an expanding spiral-like curved field among figures, with separate labels inside. Treating every path as a closed concentric ring is unsupported. Gold stars, figure outlines and central animal are drawing; faint outer strings remain partly unknown.',writing_paths='spiral-like curved strings and figure labels, not forced closed rings',visible_panel_fractions=[],orientation='local tangent changes continuously; start/end and branch relations partly unknown'),
 'V_135':dict(observation='Curved expanding writing field has distinct label strings near figures and central seated figure/device. Native crops separate tall-frame-like written constructions from raised figure arms/stars. Several drawing-writing contacts and faded lower strings remain unknown.',writing_paths='expanding curved/spiral strings plus separate figure labels',visible_panel_fractions=[],orientation='changing local tangent, no certified closed-ring seam'),
 'V_157':dict(observation='Three writing/layout fields separated by visible vertical creases: left curved bands/short paragraphs, central annular bands and lower paragraph, right dense straight paragraph. Blue scallops, spokes, central faces and plume/wave outlines are drawing. Native ring crops retain writing-unit contacts and visible gaps without forcing a seam.',writing_paths='left curved/radial bands; central annular strings; separate straight fields',visible_panel_fractions=[.395,.70],orientation='independent ring tangents and straight paragraph x'),
 'V_159':dict(observation='Large rosette sheet has multiple circular writing bands and rotated connector labels. Blue scallops, towers, waves, star patterns and repeated small ornament are drawing, not minim sequences. A horizontal crease and two vertical creases divide capture regions while several written bands cross them.',writing_paths='multiple annular/curved bands and rotated connector labels',visible_panel_fractions=[.405,.725],visible_horizontal_panel_fractions=[.50],orientation='each rosette/connector has its own path; no common line x position'),
}
PANELS={
 'V_128__V_129':dict(observation='Distinct circular figure fields, one with two central animals and one with single animal. V128 has a visible internal vertical crease around x0.37; V129 has no comparable internal crease. Shared caption does not resolve physical side identity or a common writing field.',visible_divisions={'V_128':[.37],'V_129':[]}),
 'V_132__V_133':dict(observation='V132 shows two faint circular fields with internal/dividing creases around x0.25/0.59. V133 shows a different single circular field with central device and substrate hole. No shared writing-field transform accepted.',visible_divisions={'V_132':[.25,.59],'V_133':[]}),
 'V_156__V_157':dict(observation='V156 is a narrow straight-writing capture; V157 is a wide curved/annular/paragraph capture divided around x0.395/0.70. Field appearance and caption are insufficient to identify duplicate writing; no overlap transform accepted.',visible_divisions={'V_156':[],'V_157':[.395,.70]}),
 'V_157__V_158':dict(observation='V158 is a separate opened configuration with dense left paragraph and right upper/middle/rotated writing fields divided near x0.47. V157 has distinct circular fields and right paragraph. No shared written region is established from these captures.',visible_divisions={'V_157':[.395,.70],'V_158':[.47]}),
 'V_164__V_165':dict(observation='V164 shows plant/container fields with internal fold around x0.40; V165 opens three major writing/illustration fields with creases near x0.395/0.715. Folds explain multiple capture fields but do not certify overlap or caption-side identity.',visible_divisions={'V_164':[.40],'V_165':[.395,.715]}),
 'V_165__V_166':dict(observation='Wide V165 has multiple illustrated/writing fields; narrow V166 is a different plant with lower paragraphs. No common writing field or within-V166 internal panel division certified.',visible_divisions={'V_165':[.395,.715],'V_166':[]}),
 'V_172__V_173':dict(observation='Distinct narrow plant/text views, without a clear internal foldout panel boundary in either. Similar layout is insufficient for writing deduplication. Container/bud outlines must remain drawing rather than written loops.',visible_divisions={'V_172':[],'V_173':[]}),
 'V_180__V_181':dict(observation='Narrow V180 and wide V181 show different plant/container writing fields. V181 has visible divisions near x0.365/0.68/0.905, some partly folded. No exact shared written area accepted.',visible_divisions={'V_180':[],'V_181':[.365,.68,.905]}),
 'V_182__V_183':dict(observation='Distinct narrow plant/container/text captures with curled lower edges and show-through. These do not certify a shared written field or a complete physical-panel correspondence. Large stains and plant contours stay nonwriting/unknown at overlaps.',visible_divisions={'V_182':[],'V_183':[]}),
}

def main():
    root=OUT/'data/observations/source_adjudication_v2';q=read_json(root/'queue_plan.json');curves=[];panels=[]
    for case in q['curved_views']:
        if case['view_id'] not in CURVES:continue
        curves.append(dict(case,**CURVES[case['view_id']],status='source_reviewed: writing paths distinguished from diagram/ornament; unit boundaries partly unknown',native_inspection='whole capture plus four unscaled 650x650 source crops',group_boundaries='unknown except visible local gaps; no complete ring group inventory certified',pen_lift='unknown',horizontal_assay_eligible=False))
    for pair in q['foldout_pairs']:
        key=pair['from_view']+'__'+pair['to_view']
        if key not in PANELS:continue
        panels.append(dict(case_id='PANEL_'+key,from_view=pair['from_view'],to_view=pair['to_view'],**PANELS[key],status='source_reviewed',physical_folio_identity='unknown beyond caption evidence',accepted_overlap_transform=None,do_not_infer='Visible creases partition capture fields; they do not certify physical leaves/bifolios or duplicate writing.'))
    write_json(root/'curved_judgments.json',curves);write_json(root/'panel_judgments.json',panels)
    print('Reviewed',len(curves),'curved views and',len(panels),'panel pairs',flush=True)

if __name__=='__main__':main()
