"""Source gap/membership review after connected-body reconstruction, before assays."""
from common import OUT,read_json,write_json
from datetime import datetime,timezone

REVIEWS={
 'V_042':dict(cuts=[610,780,887,980,1215,1455,1565,1760],unknown_groups=[1,3,5,6,9],observation='Body row recovered, including tall structures previously omitted. Long lower-row contacts at several positions remain unknown. Interior source gaps broadly visible; dense stain area cannot certify all ink membership.'),
 'V_017':dict(cuts=[716,875,1040,1220,1475,1595,1755,1825],unknown_groups=[1,3,4,8],observation='Separate written groups visible within previous giant first group. Plant removed; patchy substrate at middle and plant-edge terminal return remain unknown. Two fields are a physical row hypothesis, not a sentence.'),
 'V_007':dict(cuts=[930,1100,1292,1455,1640,2010,2260],unknown_groups=[1,4,6],observation='Sloping lower body recovered; tall upper/lower contacts and long descending return remain ambiguous. Plant stem excluded. Source-visible broad gaps restore more slots than full-component union.'),
 'V_032':dict(cuts=[595,740,850,1140,1350,1510],unknown_groups=[5,6,7],observation='Writing clearly separate from plant. Most lower-body groups complete, but last tall structures overlap lower-row ascenders and plant edge. Internal narrow gaps retained as hypothesis, not word boundaries.'),
 'V_015':dict(cuts=[853,1030,1210],unknown_groups=[1,3,4],observation='Flower removed and writing row recognizable. Visible gap before first paired-tall group; upper descender and lower tall contacts remain ambiguous. Last endpoint near flower is uncertain.'),
 'V_033':dict(cuts=[700,825,930,1035,1115,1335,1450],unknown_groups=[1,2,3,4,5],observation='Source slope correction recovers writing body. Several left gaps are obscured by texture/shaded substrate, so no complete boundary model certified there; right paired/frame groups are clearer.'),
 'V_027':dict(cuts=[1074],unknown_groups=[1,2],observation='Corrected source slope recovers paired tall trace. Two broad source clusters; narrow internal whitespace is not promoted to a group. First connected construction has neighboring-row contact; small pale marks remain unknown.'),
 'V_025':dict(cuts=[936,1020,1242,1445,1600,1725,2025,2225],unknown_groups=[1,3,4,7],observation='Red stem excluded; target body seed initially too low, omitting left loops. Adjust source seed upward. Clear broad whitespace on both sides; plant interruption remains a physical-row hypothesis.'),
 'V_045':dict(cuts=[946,1158,1295,1510,1655],unknown_groups='all',primary_eligible=False,observation='Corrected body recovers initial loop and tall trace, but right portion still crosses different body levels and flower border. Source row path and terminal membership unresolved; exclude whole-row positional endpoints.'),
 'V_019':dict(cuts=[],unknown_groups='all',primary_eligible=False,observation='Different left/right body levels and drawing remnants prevent one complete row. Keep source writing fields, no certified rank/pixel primary endpoint.'),
 'V_044':dict(cuts=[438,697],unknown_groups=[1,3],observation='Three writing clusters separated by broad visible gaps. Texture/stain obscures first cluster; final tall-frame joins neighboring-row trace. Retain unknown ink membership there.'),
 'V_004':dict(cuts=[],unknown_groups='all',primary_eligible=False,observation='Faint left writing partly recovered. Right fragments cannot establish same-row membership or endpoint; no whole-row positional normalization accepted.'),
 'V_070':dict(cuts=[635,940,1135],unknown_groups=[1,2],observation='Four broad writing clusters in short final row; small gap after isolated-looking tall curve is an internal alternative. Colored substrate/left connected long trace obscure ownership.'),
 'V_071':dict(cuts=[1115,1332],unknown_groups=[1,2,3],observation='Three broad writing clusters before leaf; faint initial fragment, detached upper traces and descender reaching following body remain unknown. Endpoint at leaf cannot be certified.',primary_eligible=False),
 'V_075':dict(cuts=None,unknown_groups=[1,2,4],observation='Lower body mostly recovered, but first descending return and stacked upper/lower tall contacts share ownership. Upper neighboring row at right stays unknown.'),
 'V_073':dict(cuts=[2080],unknown_groups=[1],observation='Two broad source clusters in short right final row. The first initial hooked form is adjacent to plant-cut edge; second connected tall and low trace retained whole.'),
 'V_060':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Straight sloping corridor changes between visible body levels across page and omits portions of tall structures. This is a reconstruction failure, not proof of photographic illegibility; no certified complete row.'),
 'V_086':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Source shows coherent local writing, but straight corridor mixes upper descenders and lower body traces at left and misses small right loops. Ownership model requires a traced path; current whole-row endpoints unknown.'),
 'V_057':dict(cuts=[933,1040,1145,1310],unknown_groups='all',observation='Short written final row has more visible gaps than parent union; pervasive substrate texture creates false connecting ink. Gap hypotheses retained but exact mask membership unknown.'),
 'V_085':dict(cuts=None,unknown_groups=[1,2,3,4,5],observation='Writing before/after plant recognizable. Tall uprights near middle only partially recovered and pale detached marks uncertain; last three low groups clearer. Continuation around excluded stem unknown.',primary_eligible=False),
 'V_104':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Blue pod/outline correctly excluded, but selected corridor alternates two physical writing bodies. No complete same-row membership or positional endpoint accepted.'),
 'V_095':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Mask misses source-visible upper-right writing while keeping lower-left final row and neighboring tall trace. These are different body fields. Do not label missing ink as photographic uncertainty.'),
 'V_103':dict(cuts=None,unknown_groups=[1,3,4,5,6,7],observation='Lower writing fields recognizable around plant; first includes upper loop, third detached marks, fourth/fifth plant-edge and tall contacts, final neighboring lower pair. Second broad group clearer. Row continuation across drawing unknown.',primary_eligible=False),
 'V_082':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Source faded and smeared with substrate/show-through. Writing is visible locally, but gaps and exact row ownership cannot be resolved throughout.'),
 'V_144':dict(cuts=[615,880,1055,1225,1375,1565,1663,1850],unknown_groups=[1,2,3],observation='Main middle row has broad visible source gaps. First groups include neighboring lower return and tall contact; later low/tall groups clearer. Parent-union first fragments merged in broad gap hypothesis.'),
 'V_142':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Body path rises across page; straight corridor misses right tall structure and takes lower-row forms. Coherent source writing can be traced but this candidate is not a complete physical row.'),
 'V_138':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Dense adjacent writing rows with multirow contacts. Current broad connected masks mix lower returns with target tall forms and merge several source gaps. Complete membership/boundaries not certified.'),
 'V_149':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Visible row rises then bends; straight body corridor mixes upper and lower body bands and broad source gaps. Method failure preserved, not photographic impossibility.'),
 'V_146':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Dense rows on curved substrate; ownership corridor includes lower-row tall structures and misses target upper bodies. Local writing clear, complete reconstruction failed.'),
 'V_143':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Coherent target local writing but broad middle union joins multiple groups and terminal corridor changes body levels. Shared descenders remain unknown; complete row not accepted.'),
 'V_156':dict(cuts=[580,750,803,968,1120,1190,1265,1480,1760,2095],unknown_groups=[1,2,3,4,5,8,11],observation='Broad source gaps split early union. Tall/descender shared contacts and isolated neighboring-row fragment remain unknown. Complete endpoint path still provisional.',primary_eligible=False),
 'V_140':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Vessel/drainage drawing excluded, but corridor contains connected tall/descender traces and alternate lower bodies near right. Complete source row path not certified.'),
 'V_154':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Dense writing readable locally; corridor includes different body levels at right and many long shared contacts. No full-row rank/pixel endpoint accepted.'),
 'V_110':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Selected corridor changes body level across row; left small fragments and lower tall tips mixed. Substrate stain also obscures membership. Reconstruction failed.'),
 'V_117':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Pale writing and many shared tall/descending contacts. Last broad group includes higher body traces; exact ownership and full gap inventory unknown.'),
 'V_187':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Stars/curves excluded as decoration. Source writing clear in local fields, but full corridor switches body level and includes lower paired trace at right. Not complete row.'),
 'V_196':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Dense clear writing; ownership mask visibly includes two complete body levels across right half. Reconstruction failure must not supply line rank.'),
 'V_169':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Red berry/stem drawing excluded; target paired structure at second group partly omitted and right lower body mixed. Separate writing fields retained, continuation unknown.'),
 'V_195':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Margin decoration excluded. Early union spans multiple visible gaps and later groups include shared lower return. Source writing preserved, complete boundary count unknown.'),
 'V_193':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Translucent substrate circle excluded as writing identity; its covered ink uncertain. Corridor selects different body levels and broad shared contacts; no certified full row.'),
 'V_168':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Pale leaf overlap creates photo ambiguity; central source tall structure omitted by ownership algorithm. Both photograph and reconstruction failures retained separately.'),
 'V_157':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Native right foldout paragraph clear locally, but same-y corridor switches upper/lower bodies. Physical panel identity separately unknown; complete row not accepted.'),
 'V_191':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Short paragraph row visible on left; right mask selects following body. Endpoint and source continuation unknown; method failure excluded.'),
 'V_189':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Left corridor takes lower row while right takes upper row; grouped fragments are not a complete physical writing line. Source writing remains available for revised block extraction.'),
 'V_202':dict(cuts=[465,690,815,1120,1220,1345,1510,1685,1885,2080],unknown_groups=[1,4,5,6,8,9,10,11],observation='Main target row visible across parchment, with broad gaps. Split late union at visible whitespace; missing tall trace near x1100 and shared descenders prevent admitting affected groups. Clear low groups retained.'),
 'V_188':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Mask transitions body levels between left and right and fragments target construction. Tall shared components not split; complete rank/pixel endpoint not accepted.'),
 'V_185':dict(cuts=None,unknown_groups='all',primary_eligible=False,observation='Dense source writing; very broad middle union crosses gaps, and right fragments switch body levels. Source connected long frame visible, atomicity unknown; reconstruction failure retained.'),
}

def main():
    root=OUT/'data/observations/source_adjudication_v2';q=read_json(root/'queue_plan.json');rows=[]
    for case in q['selected_rows']:
        vid=case['view_id']
        if vid not in REVIEWS:continue
        rows.append(dict(view_id=vid,parent_case_id=case['case_id'],**REVIEWS[vid],status='source_reviewed before v2 freeze and effect tests',basis='Native RGB plus exact whole-connected mask; magenta ownership unknown; source-coordinate ruler',allographic_or_grapheme_claim=False,reviewed_at_utc=datetime.now(timezone.utc).isoformat()))
    write_json(root/'boundary_judgments.json',rows);print('Recomposed boundaries reviewed',len(rows),flush=True)

if __name__=='__main__':main()
