from inventory_v6_common import *
def main():
    guard()
    if (D/'PLAN.json').exists():raise RuntimeError('Already registered')
    for p in [D,F,T,G,P]:p.mkdir(parents=True,exist_ok=True)
    dependencies={f'data/observations/visual_dataset_{v}/FREEZE_MANIFEST.json':sha256(OUT/f'data/observations/visual_dataset_{v}/FREEZE_MANIFEST.json') for v in ['v3','v4','v5']}
    dependencies.update({p.relative_to(OUT).as_posix():sha256(p) for p in [MODEL,V5/'source_reference.json',V5/'parent_class_assignments.json',V5/'group_sequences.json']})
    plan=dict(registered_at_utc=now(),version='V6 separate source structural inventory',seed=20261011,dependencies=dependencies,
      discovery='All638 V5 confirmed target writing parents. Existing311 V3 assignments frozen; source-confirmed327 UNK diagnosed before candidate classes. Nonwriting/unresolved membership excluded; competing contacts separated from resolved-parent discovery.',
      fresh_validation=dict(captions=['16','47','94'],views=['V_032','V_094','V_170'],field='First ordinary horizontal source field from existing V4 geometry, source RGB only. All primary parents in safe field reviewed, no predicted-class selection. A bad field is retained as insufficient evidence, not replaced for recurrence.',exposure='Captions unused to define V6; existing V4 image/geometry exposure and V3 source-model exposure disclosed. Not globally unseen photographs.'),
      diagnosis=dict(exclusive_precedence=['unresolved_parent_contact','insufficient_photo_or_disconnected','topology_connectivity_instability','threshold_coverage_instability','stable_source_structure_pending'],overlapping_source_tags=['V3_family_proportion_variant','recurrent_different_structure','connected_compound_candidate','appendix_branch_insertion_candidate','detached_association','source_ambiguity'],warning='Raster instability is not evidence of a new class. Visual source tags are hypotheses with unknown retained.'),
      candidates=dict(basis='Whole connected RGB-reviewed resolved writing parents only. Frozen V3 embedding and topology; complete-link distance grouping fixed before heldout assignments. No sequence inputs.',max_candidates=12,minimum_train_instances=8,minimum_train_captions=3,grouping_distance=.35,topology_exact=True,radius='90th percentile leave-caption-out nearest exemplar distance; radius capped0.35',alternative_margin=1.08,source_review='Native RGB examples must exhibit the same whole-parent organization; variants/composites remain separate descriptions, not V3 merges.'),
      composition=dict(primary='Whole connected parent retained',search='Four outside-band removals at0.20/0.30/0.40 parent extent; base requires frozen V3 fit and threshold/slant agreement; residual15..45 percent ink and connected to retained base at primary threshold. Measurement factor only; no pen lift, grapheme or order asserted.',validation='Composition candidates must recur on>=3 train captions,>=3 fresh captions and>=5 fresh parents; same native pair standards as whole-parent candidates; unvalidated factors never substitute class tokens.',competing='Record all successful base/window explanations, never choose by sequence completeness'),
      validation_gates=dict(train_instances_min=8,train_captions_min=3,fresh_stable_instances_min=5,fresh_captions_min=3,positive_pair_n_min=10,positive_agreement_min=.85,negative_pairs_min=20,false_grouping_max=.10,threshold_stability_min=.90,alignment_stability_min=.90,source_parent_resolved_required=True),
      pair_audit='Anonymous randomized RGB-only pairs, class/kind hidden. Positive n10 per eligible class from distinct fresh/training pairings where available; negative n20 per class using closest topology-matched nonmember. Unknown judgments counted as failure/abstention. Same AI adjudicator, not independent human-rater validation.',
      abstention='Any unresolved parent contact, insufficient image, inconsistent topology/contact under6/9/12, class-margin failure, rejected visual organization, or failed class gate remains UNK. V3 assignments never changed.',
      stages=['preregister','diagnose all V5 confirmed UNK/source atlas','test base/residual factors','derive source-reviewed separate candidates','seal candidates before heldout inference','fresh source confirmation seal before test assignments','heldout inference and masked native pair validation','freeze V6 inventory including failures','only then reuse unchanged V5 sequence partitions','support assessment'],
      downstream=dict(previous_v5_source_support_all_required=True,unknown_confirmed_rate_max=.20,complete_rows_min=12,complete_groups_ge3_min=100,heldout_groups_ge3_min=30,heldout_recurrence_min=.20,all_gaps_required=True),
      forbidden=['EVA','RF','v101','Currier','positional outcomes','decipherment','minimal-pair support','sequence recurrence for training or class selection'])
    save(D/'PLAN.json',plan);print('Registered V6 discovery638 parents; fresh validation3 captions; no sequence training',flush=True)
if __name__=='__main__':main()
