from dm2_robustness_common import *
from PIL import Image,ImageDraw
import numpy as np
from collections import Counter
def gallery(pairs,loc):
    for start in range(0,len(pairs),12):
        rr=pairs[start:start+12];can=Image.new('RGB',(1440,940),'#eee');dr=ImageDraw.Draw(can)
        for k,p in enumerate(rr):
            x=k%3*480;y=k//3*235;dr.text((x+5,y+4),p['repeat_id'],fill='black')
            for side,idx in enumerate(p['display_indices']):
                r=loc[idx];im=Image.open(OUT/r['native_crop']).convert('RGB');scale=min(4,225/im.width,185/im.height);im=im.resize((max(1,round(im.width*scale)),max(1,round(im.height*scale))),Image.Resampling.NEAREST);xx=x+5+235*side;yy=y+27;can.paste(im,(xx,yy));a,b=r['crop_origin'];c,d,e,f=r['native_bbox'];dr.rectangle((xx+(c-a)*scale,yy+(d-b)*scale,xx+(e-a)*scale,yy+(f-b)*scale),outline='#b35')
        can.save(G/f'anonymous_repeat_{start//12+1:02d}.png')
def main():
    guard();assert not (D/'PROTOCOL_SEAL.json').exists();verify_base()
    for folder in [D,T,G,P]:folder.mkdir(parents=True,exist_ok=True)
    oldpost=OUT/'tests/direct_morphology_trial2_postfreeze';seal([p for p in oldpost.rglob('*') if p.is_file()],D/'PRIOR_POSTFREEZE_SNAPSHOT.json')
    plan=dict(registered_at_utc=now(),study='Postfreeze Direct Morphology Trial2 robustness investigation v1',seed=20261023,previous_result_known=True,independent_validation=False,not_a_new_validation_pass=True,metric='Immutable primary contour64 only; aspect-only baseline retained, no SDF/resolution/learned substitution',base_manifest_sha256=sha256(B/'FREEZE_MANIFEST.json'),source_population='Frozen360 used source pairs only; unused240 remain unopened. Frozen source judgments and all extents unchanged.',
        source_filters=dict(all='All frozen used pairs; original whole extent qualification remains',extent_clean='Both parents resolved extent and no frozen possible_join/possible_split/detached_association_unknown/faint_or_insufficient_extent/neighboring_row_contact_possible flags. Report if this excludes nothing; do not invent ambiguity.',recovery_clean='Both parents have no missing/split/merge flags in frozen6/12 contrast correspondence; exactly one observed matching candidate at each contrast. Synthetic slant is not source ambiguity.',extent_and_recovery_clean='Intersection of the two preceding filters',field_edge_sensitivity='Further exclude frozen field_edge_location_aid; field edge is an extraction aid, not certified physical extent ambiguity. Connected compound flag alone does not exclude an already source-resolved whole parent.'),
        matching=dict(eligibility='Original binary0/2 only for primary conservative matching; no same/different or distance objective',method='Maximum-cardinality binary edge matching using parent<=1 constraints; seeded random-priority secondary objective fixing maximal count. Parent+dyad adds dyad<=1. Dyad-only also reported. Caption dependence remains even with disjoint parents.',tie_seed_rule='Base seed plus deterministic analysis index; solve cardinality first then seeded priority; retain selected IDs and solver optimality/replay',strata='Pooled, broad_random, aspect_matched separately; refit only subset-selection constraints, never the metric',selection_variability='50 additional seeded greedy label/distance-blind admissible subsets for each binary condition. These distributions are selection sensitivity, not statistical confidence intervals; no best subset chosen.'),
        contrasts=dict(binary='2vs0, partial excluded exactly as frozen',partial_as_same='2/1 positive versus0 negative',partial_as_different='2 positive versus1/0 negative',same_vs_partial='2 positive versus1 negative',partial_vs_different='1 positive versus0 negative',recoding_interpretation='Two uniform partial recodings are sensitivity endpoints, not truths or sharp bounds over every mixed allocation of partials.'),
        analysis_matrix='For each source filter and each sampling stratum: original binary under pooled, parent<=1,dyad<=1,parent+dyad<=1. Adjacent contrasts and uniform recodings separately for all/recovery-clean/combined-clean, pooled and both strata, without independence constraints; additionally disjoint-parent pooled contrasts. No contour-based pair selection.',
        uncertainty=dict(bootstrap_n=5000,method='Frozen-style two-endpoint caption/node bootstrap weights=count(left)*count(right), same weights for contour and aspect. Use all eight original captions in every analysis. Fixed draws shared across subsets; zero-weight edges omitted by weighting. Exact weighted MannWhitney AUROC ties=.5.',report='Point AUROC, counts, unique parents, caption/dyad support, valid bootstrap fraction and conditional95% interval for every mathematically estimable condition. Confidence evidence considered adequate only with each category>=5, each spanning>=3 captions,>=4 captions overall and>=4500 valid draws. Smaller subsets remain descriptive, not failed by substitution.',partial='Partial inclusion changes the target and membership counts; uncertainty conditional on original labels. No relabeling used to replace frozen success criteria.'),
        repeat=dict(n=125,target_original_counts={'2':35,'1':45,'0':45},selection='All35 original same pairs plus seeded uniform45 of149 partial and45 of176 different; shuffle all anonymous IDs and sides. Adequate positive category limited by frozen35. No distance/uncertainty/previous repeat selection.',blind='Native RGB pair crops only; original IDs/categories/distances/neighbors/stratum hidden. Original result and earlier source exposures known; same-adjudicator memory not eliminated. No independent human validation.',rubric='2 same whole visible organization allowing ink/size/slant variation;1 partial/related;0 different;U unresolved. Do not force binary, infer strokes or writing identities.',separation='Intervening sealed matching preparation and source-integrity checks, changed IDs/sides; short-session/global memory limitation disclosed.',statistics='Exact all-category agreement, linear ordinal agreement1-|a-b|/2 and quadratic1-(a-b)^2/4 on resolved0/1/2, unweighted/linear/quadratic Cohen kappa, transition counts and per-original-category retention including U. Original-category-frequency reweighting alongside balanced-repeat sample. Caption-aware conditional intervals; source labels not overwritten.',prediction_diagnostic='Original and repeat binary AUROC on the same125 selected pairs, plus disagreement-excluded diagnostic; preserve changed label membership and original-selection conditioning. Separate labels, never replace original.'),
        interpretation=dict(rule='No new validation pass or modification to Trial2. Unsupported under conservative analysis only if both adequate disjoint-parent original-binary and source+recovery-clean disjoint-parent results have AUROC<=.5 or upper95%<=.5. Sensitive if an adequate subset drops>=.10 AUROC relative to pooled baseline, a stratum has contour-aspect advantage<=0 with stratum AUROC gap>=.10, uniform partial-recoding AUROC range>=.10 or either recoding drops>=.10, or repeat same/different retention<.80 or repeat-relabelled binary AUROC drops>=.10. Otherwise robust with important qualifications if any key subset is underpowered, partial retention<.80/exact agreement<.85, adjacent contrast AUROC<.65 or lower95%<=.5. Robust only if no listed sensitivity/qualification applies. These interpretive conventions describe robustness, not retrospective changes to frozen success criteria.',underpowered='Do not call a sparse conservative subset failed merely because a meaningful interval cannot be estimated; report loss of support explicitly.'),
        prohibited='All conventional transcription/Currier/position/sequence/decipherment and V3-class information remain sealed',freeze='Separate package includes protocol, selected subsets, anonymous repeat judgments, all contour64-only analyses, replay, failures and integrity. Prior frozen and prior postfreeze evidence untouched.')
    save(D/'PLAN.json',plan);seal([D/'PLAN.json',D/'PRIOR_POSTFREEZE_SNAPSHOT.json',OUT/'src/dm2_robustness_common.py',OUT/'src/register_dm2_robustness.py'],D/'PROTOCOL_SEAL.json')
    ratings=read_json(B/'source_similarity_decisions.json')['pairs'];key={r['pair_id']:r for r in read_json(B/'pair_pool_hidden_key.json')['pairs']};rng=np.random.default_rng(plan['seed']);chosen=[]
    for cat,count in [(2,35),(1,45),(0,45)]:
        pool=[r['pair_id'] for r in ratings if r['rating']==cat];chosen.extend(rng.choice(pool,count,replace=False).tolist())
    rng.shuffle(chosen);rows=[];hidden=[]
    for i,pid in enumerate(chosen):
        p=key[pid];sides=[p['left_index'],p['right_index']];rng.shuffle(sides);rid=f'J{i+1:03d}';rows.append(dict(repeat_id=rid,display_indices=sides));hidden.append(dict(repeat_id=rid,original_pair_id=pid))
    gallery(rows,read_json(B/'source_location_aids.json')['parents']);save(D/'repeat_hidden_key.json',dict(pairs=hidden,category_counts=plan['repeat']['target_original_counts'],no_distance_selection=True));save(D/'repeat_display_mapping.json',dict(pairs=rows))
    seal([D/'repeat_hidden_key.json',D/'repeat_display_mapping.json']+list(G.glob('anonymous_repeat_*.png')),D/'REPEAT_POOL_SEAL.json');print('Robustness protocol sealed;125 anonymous source pairs prepared',flush=True)
if __name__=='__main__':main()
