from feature_trial2_common import *
from neutral_feature_trial_v1 import DEFS as PREVIOUS
from pathlib import Path
import math
DEFS=dict(PREVIOUS)
DEFS['log_height_body']=('geometry',.40,'log envelope height/body proxy; full image and±10% reference interval')
DEFS['log_width_body']=('geometry',.40,'log envelope width/body proxy; full image and±10% reference interval')
DEFS['log_height_native']=('native_dimensions',.18,'log native ink-envelope height in source pixels, interval retained')
DEFS['log_width_native']=('native_dimensions',.18,'log native ink-envelope width in source pixels, interval retained')
CORE=['log_height_body','log_width_body','log_aspect','ink_density','ink_centroid_x','ink_centroid_y','ink_spread_x','ink_spread_y']+[f'ink_grid_{y}{x}' for y in range(3) for x in range(3)]+['significant_cavity_count','cavity_area_fraction','cavity_centroid_x','cavity_centroid_y','cavity_upper_count','cavity_lower_count','horizontal_run_fraction','vertical_run_fraction']
def main():
    guard()
    if (D/'PLAN.json').exists():raise RuntimeError('Already registered')
    for p in [D,T,G,P]:p.mkdir(parents=True,exist_ok=True)
    dependencies={f'data/observations/visual_dataset_{v}/FREEZE_MANIFEST.json':sha256(OUT/f'data/observations/visual_dataset_{v}/FREEZE_MANIFEST.json') for v in ['v3','v4','v5','v6']}
    deps=[OUT/'data/observations/neutral_feature_trial_v1/EVIDENCE_SEAL.json',MODEL]
    dependencies.update({p.relative_to(OUT).as_posix():sha256(p) for p in deps})
    fields=[]
    rows=read_json(OUT/'data/observations/sequence_v4_development/source_rows.json')
    for cap in CAPTIONS:
        r=next(r for r in rows if r['folio_component']==cap and r['status']=='triaged_local_writing_field');fields.append({k:r[k] for k in ['view_id','row_number','safe_x','body_height','body_path_knots','native_source','source_row_bbox']})
        fields[-1]['caption']=cap
    assert not set(CAPTIONS).intersection({'5','10','34','39','55','81','106','115','16','47','94'})
    plan=dict(registered_at_utc=now(),trial='Neutral Structural Feature Profiles Trial2',seed=20261015,dependencies=dependencies,
      question='Can partial source-qualified feature profiles describe most confirmed writing, including class-resistant forms, and predict heldout visual similarity?',
      methodology_changes=dict(basis='Trial1 overall descriptor perturbation results and documented normalization/semantic limitations, not V3-class-stratified rates or downstream outcomes.',retained='Aspect, density, centroid/spread,3x3 ink distribution, run and cavity measurements; original tolerances retained except dimensions.',secondary='Skeleton endpoints/branches, component count and redundant thirds retained but neither required for usability nor used in similarity distances. Native dimensions recorded separately and excluded from cross-capture similarity.',normalization='Full body±10% reference range log(1.1/0.9)=0.20067 plus permitted native log-dimension measurement span0.18 totals0.38067. Fixed0.40 normalized tolerance accommodates both; native log dimensions retain0.18 tolerance. No body-scale perturbation can alone force failure.',source_qualification='Raw raster repeatability and source-visible feature evidence remain separate. Cavity descriptors enter source-qualified core profiles only with matching resolved source-visible count; upper/lower/centroid fields additionally require resolved compatible source placement. Counts disagreeing with source or unaudited remain source-unknown, never imputed.'),
      features={k:dict(family=v[0],range_tolerance=v[1],definition=v[2],core=k in CORE) for k,v in DEFS.items()},
      core_features=CORE,usable='Confirmed writing and resolved whole parent, unique whole-parent raster correspondence across6/9/12(IoU>=0.5, no split/merge),>=8 stable source-qualified core fields, geometry+distribution+at least run or cavity. Source contacts/insufficient evidence block usability; all confirmed writing remains in primary coverage denominator. Secondary graph failures do not block.',
      perturbations=['native9/6/12 whole-parent rasters','native±0.04 slant','source-body±10%'],
      samples=dict(reference='Seeded up to8 source-resolved confirmed parents in each of11 Trial1 caption groups; no class selection; reference image features source-audited after specification. Historical source data additionally reported as sensitivity, not fresh test.',fresh_fields=fields,selection='First existing overview-triaged ordinary horizontal field per6 captions unused for Trial1/V6 feature tuning, source-only geometry/contrast/layout. All primary CC proposals with area>=35 and core support>=8 inspected. Photographic failure retained; no replacement based on results. Report parent-proposal sampling limits, not full writing-ink recall.',exposure='Some source captions had old V3/V4 imagery exposure; fresh for Trial2 specification, not globally unseen photographs.',source_membership='Every selected proposal reviewed native RGB/whole field before feature/V3 suggestions; nonwriting/unresolved excluded from confirmed denominator but enumerated. Visible missing parent fragments may be added as explicit source cases, never assumed recovered.'),
      source_audit=dict(all_new_and_reference=True,questions=['writing/nonwriting/unresolved','whole-parent contact or insufficient evidence','visible cavity count or unknown','cavity placement upper/lower/both/none/unknown relative envelope mid-height, near-midpoint±0.05 ambiguous','coarse source aspect taller(W/H<0.8)/wide(>1.25)/near-square/unknown','evident long near-horizontal source span/absent/unknown'],same_AI_adjudicator=True,not_independent_interrater=True,numeric_and_V3_suggestions_hidden=True,definition_discordance='Visible vs significant raster cavities can differ; score agreement and source qualification separately without retuning cutoff.'),
      similarity=dict(profile_distance='Equal-weight family means of stable shared-core absolute midpoint differences divided by preregistered tolerance(counts scale1), clipped3. Geometry/distribution/run/cavity. At least8 shared fields and geometry+distribution+run/cavity. Add0.10*(1-shared_core/25) observability penalty. No learned label weights.',baselines=['absolute log aspect difference','symmetric24px contour Chamfer from frozen aspect-preserving48px normalization','50/50 contour+aspect, each scaled by reference-only cross-caption95th percentile and clipped1'],pairs='Seeded up to12 resolved writing anchors per fresh caption. For each: closest eligible feature reference, closest contour reference, and seeded aspect-matched(log aspect difference<=0.35) random reference. Deduplicate; retain selector provenance. Pair proposals formed without V3 labels or source similarity outcomes.',source_judgment='Randomized anonymous RGB pairs, predictions/selectors/V3 hidden; rate2=same whole visual organization allowing ink/size/slant variation,1=partial shared organization,0=different organization,U=unresolvable. These pair judgments do not define transitive discrete classes or internal units.',metrics='Primary AUROC rating2 vs0; exclude1/U but report all four counts. Secondary ordinal association on0/1/2. Paired6-caption bootstrap of AUROC differences; reference/anchor repeats acknowledged. No fit on test judgments.',better_than_baseline_gate='Feature AUROC≥0.75; delta≥0.05 with bootstrap95% lower>0 against each of aspect,contour,combined;>=120 resolved2/0 pairs,>=30 per category and6 captions. If not, preserve failure, no feature/weight tuning.'),
      V3_diagnostics='Only after source decisions/feature specification/metric seal. Apply frozen V3 unchanged to fresh resolved writing. Existing source labels projected for reporting only. Known-family cross-caption feature distances vs within-caption shuffled labels(999 nulls), classes with>=5 parents and>=3 captions; no learned class metric. Report coherence and leave-caption retrieval without altering profiles.',
      unknown_recurrence='Continuous neighborhood evidence, not clusters: threshold distance<=0.25 with>=8 common core and3 families; count unknown confirmed parents having a neighbor in another caption and support in>=3 captions. Reference-to-fresh transport separately. Null999 within-caption independent whole-family vector permutations retaining missingness and exact caption size; observed/null both dependence-limited. No new class label, equivalence relation or sequence token.',
      validation_gates=dict(fresh_confirmed_n_min=120,fresh_caption_n_min=6,overall_usable_confirmed_min=.80,resolved_usable_min=.85,each_caption_overall_min=.70,V3_unknown_usable_confirmed_min=.70,source_cavity_adjudicable_n_min=50,source_cavity_numeric_agreement_min=.85,source_aspect_agreement_min=.85,source_uncertainty_preserved=True,deterministic_replay_required=True),
      acceptance='Coverage/source agreement and similarity superiority are separate gates. Report descriptive partial-profile support separately from prediction superiority; no single combined accuracy score. No classes required to occupy compact regions; coherent V3/unknown neighborhoods remain validation results, not tuning inputs.',
      stages=['seal protocol before fresh images','prepare and source-adjudicate all reference/new objects and visual fields','seal source judgments before feature suggestions','extract fixed features/source qualification','seal metric inputs before similarity rating/V3 analyses','anonymous heldout similarity review and repeat subset','V3 diagnostic and continuous unknown recurrence tests','report all failures/support thresholds','freeze Trial2 before any position/section/transcription/sequence correlation'],
      repeat='Seeded12 similarity pairs shown anonymously again after source/feature work with original IDs and decisions hidden. Same-adjudicator repeatability only; unresolved/ties retained.',
      prohibited_tuning=['V3 membership','sequence recurrence','Currier','EVA/RF/v101','positional effects','decipherment outcomes'],
      downstream='No position, section, conventional transcription or sequence correlation before Trial2 freeze; this task does not authorize reopening them afterwards.')
    save(D/'PLAN.json',plan);seal([D/'PLAN.json',Path(__file__),OUT/'src/feature_trial2_common.py'],D/'SPECIFICATION_SEAL.json');print('Preregistered Trial2:36 fields/25 core;6 fresh captions;source qualification and similarity baselines sealed',flush=True)
if __name__=='__main__':main()
