from inventory_v6_common import *
SOURCE={
 'NC01':('reject','Mixes compact ring without appendix, arch with descending right trace and paired minima. Raster hole count0 does not make these the same source structure.'),
 'NC02':('retain_candidate','Vertically stacked lobes joined at a narrow waist, one significant raster hole and a bulky/filled upper region. A source family/compound variant hypothesis, not a new grapheme; upper/lower cavity placement must agree in native pair review.'),
 'NC03':('reject','Horizontal bench-like frame, repeated low arches and short thick terminals mixed. Different bridge/upright organization; cannot merge for coverage.'),
 'NC04':('reject','Open/closed/filled compact forms and loop with right descending branch mixed despite stable one-hole raster labels.'),
 'NC05':('reject','Compact rings and rings/arches with substantial right appendix mixed. Added appendices remain competing interpretations.')}
def main():
    guard();assert not (D/'fresh_assignments.json').exists();verify_seal(D/'DEVELOPMENT_AMENDMENT_SEAL.json');whole=read_json(D/'calibrated_whole_candidate_discovery.json')
    for r in whole['candidates']:
        r['source_decision'],r['source_structure']=SOURCE[r['candidate_id']]
    save(D/'source_candidate_reviews.json',dict(created_at_utc=now(),whole_candidates=whole['candidates'],review='All native RGB examples in five training-only galleries, no test suggestions.',composition_families={k:dict(source_decision='reject_reusable_composite_class',reason='The same cut family includes arbitrary truncation through lobes, uprights and bridge bodies. Native factor gallery lacks recurring appendix/insertion organization. Primary base fit alone is insufficient.') for k,v in read_json(D/'composition_discovery.json')['candidates'].items() if v['eligible']},plausible_individual_factor_examples=['B012_O040','B014_O071'],factor_example_reason='Lower frame with upper loop/upright/arc can be described as geometry; two examples do not validate a reusable8-instance3-caption composite family.',no_train_examples_removed_to_make_class_homogeneous=True))
    save(D/'sealed_candidate_model.json',dict(created_at_utc=now(),v3_model_sha256=sha256(MODEL),whole_candidates=whole['candidates'],assignable_candidate_ids=[c['candidate_id'] for c in whole['candidates'] if c['source_decision']=='retain_candidate'],validated_classes=[],composition_assignable=[],radius_margin=1.08,source_parent_resolved_required=True,perturbations='Native6/9/12 whole-parent masks; fixed V3 slant transform; exact stable topology/contact required',class_overlap='Retain V3 assignment always; new candidate applies only to confirmed-writing UNK. Separate namespace; no V3 fit or threshold change.'))
    seal([D/'sealed_candidate_model.json',D/'source_candidate_reviews.json',D/'calibrated_whole_candidate_discovery.json',D/'whole_candidate_embedding.npz',D/'composition_discovery.json',D/'PLAN.json',D/'DEVELOPMENT_AMENDMENT.json',Path(__file__)],D/'CANDIDATE_MODEL_SEAL.json');print('Sealed NC02 only; four source-mixed whole candidates and three generic factor families rejected before test',flush=True)
if __name__=='__main__':main()
